// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the NativeMobileResources module

	public static java.lang.String getNative_Mobile_Resources_Version()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("NativeMobileResources.Native_Mobile_Resources_Version");
	}
}