// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} localStorageKey
 * @param {string} objectItemKey
 * @returns {Promise.<string>}
 */
export async function JS_GetSingleLocalStorageObjectItem(localStorageKey, objectItemKey) {
	// BEGIN USER CODE
	if (!localStorageKey) {
        return Promise.reject(new Error("Input parameter 'localStorageKey' is required"));
    }
    if (!objectItemKey) {
        return Promise.reject(new Error("Input parameter 'objectItemKey' is required"));
    }
	const localObject = window.localStorage.getItem(localStorageKey);
	const parsedObject = JSON.parse(localObject);
	const singleItem = parsedObject?.[objectItemKey] ?? "";
	
	return Promise.resolve(singleItem);
	// END USER CODE
}
