// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<boolean>}
 */
export async function JS_isStrictMode() {
	// BEGIN USER CODE
    return new Promise(resolve => {
        try {
            mx.data.create({
                entity: "FeedbackModule.Feedback",
                callback: obj => {
                    mx.data.remove({
                        guid: obj.getGuid(),
                        callback: () => resolve(false),
                        error: () => resolve(false)
                    });
                },
                error: () => resolve(false)
            });
        } catch (err) {
            if (err.message.includes("mx.data.create is disabled")) {
                resolve(true);
            } else {
                resolve(true);
            }
        }
    });
	// END USER CODE
}
