// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import { getUserRoleNames } from "mx-api/session";
import { ui, session } from "mx-api";

// BEGIN EXTRA CODE
    const handleUserRoles = async () => {
        try {
            let userRoles;

            if (
                typeof mx !== "undefined" &&
                typeof mx.session === "object" &&
                typeof mx.session.getUserRoleNames === "function"
            ) {
                userRoles = mx.session.getUserRoleNames();
            } else if (typeof getUserRoleNames !== "function" || getUserRoleNames === undefined) {
                userRoles = getUserRoleNames();
            } else {
                console.error("Feedback module cannot access a valid user role retrieval function.");
                return undefined;
            }

            if (!Array.isArray(userRoles) || userRoles.length === 0) {
                console.error("User roles not available or empty.");
                return undefined;
            }

            return userRoles[0];
        } catch (error) {
            console.error("Feedback module failed to get the user role name.", error);
            return undefined;
        }
    };

    const handlePagePath = async () => {
        try {
            if (
                typeof mx !== "undefined" &&
                typeof mx.ui.getContentForm === "function" &&
                typeof mx.ui.getContentForm().path !== "undefined"
            ) {
                return mx.ui.getContentForm().path;
            } else {
                return window.history.state.pageName;
            }
        } catch(error) {
            console.error("Feedback module cannot get the Mendix App page name", error);
            return undefined;
        }
    };
// END EXTRA CODE

/**
 * What does this JavaScript action do?
 * 
 * Returns meta data from the clients internet browser. 
 * 
 * This includes; 
 * 
 * ActiveUserRoles
 * PageName
 * EnvironmentURL
 * Browser
 * ScreenWidth
 * ScreenHeight
 * @param {MxObject} feedback
 * @returns {Promise.<MxObject>}
 */
export async function JS_PopulateFeedbackMetadata(feedback) {
	// BEGIN USER CODE
    try {
        const userRoles = await handleUserRoles();
        const pagePath = await handlePagePath();

        feedback.set("ActiveUserRoles", userRoles || "");
        feedback.set("PageName", pagePath || "");
        feedback.set("EnvironmentURL", window.location.href || "");
        feedback.set("Browser", navigator.userAgent || "");
        feedback.set("ScreenWidth", window.screen.width || "");
        feedback.set("ScreenHeight", window.screen.height || "");
        return feedback;
    } catch (error) {
        console.error("Feedback Module cannot correctly set meta data.", error);
    };
	// END USER CODE
}
