// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function JS_Recalculate_MendixModal_Error_PopUp_Zindex() {
	// BEGIN USER CODE

	function setModalZindex(cssSelector, zIndexValue) {
		try {
			const htmlElement = document.querySelectorAll(cssSelector);

			if(!htmlElement.length) {
				return;
			}

			htmlElement.forEach(item => item.style.zIndex = zIndexValue);

		} catch(error) {
			console.warn("Feedback Module JS Action JS_Recalculate_Modal_Zindex could not execute correctly.", error);
		}
	};

	setTimeout(() => {
		setModalZindex(".mx-dialog-info, mx-dialog-warning, .mx-dialog-error", "90");
		setModalZindex(".mx-underlay", "80");
	},500);
	// END USER CODE
}
