// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} localStorageKey
 * @param {string} imageDataB64
 * @returns {Promise.<void>}
 */
export async function JS_SetSingleLocalStorageObjectItem(localStorageKey, imageDataB64) {
	// BEGIN USER CODE
    if (!localStorageKey) {
        return Promise.reject(new Error("Input parameter 'localStorageKey' is required"));
    }

    const existingData = window.localStorage.getItem(localStorageKey);
    let parsedData = {};

    if (existingData) {
        try {
            parsedData = JSON.parse(existingData);
        } catch (error) {
            console.warn(`Failed to parse existing localStorage data. Overwriting.`, error);
        }
    }

    parsedData.ImageB64 = imageDataB64;

    window.localStorage.setItem(localStorageKey, JSON.stringify(parsedData));
    return Promise.resolve();
	// END USER CODE
}
