import { Base64 } from 'js-base64';

// This file was generated by Mendix Studio Pro.
/**
 * @param {string} string
 * @returns {Promise.<string>}
 */
async function Base64Encode(string) {
    // BEGIN USER CODE
    return Base64.encode(string);
    // END USER CODE
}

export { Base64Encode };
