// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_designsystem.proxies;

public class Accordion
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject accordionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Atlas_DesignSystem.Accordion";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Expanded("Expanded"),
		ExpandedExpression("ExpandedExpression");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Accordion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Accordion(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject accordionMendixObject)
	{
		if (accordionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, accordionMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.accordionMendixObject = accordionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Accordion.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static atlas_designsystem.proxies.Accordion initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return atlas_designsystem.proxies.Accordion.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static atlas_designsystem.proxies.Accordion initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new atlas_designsystem.proxies.Accordion(context, mendixObject);
	}

	public static atlas_designsystem.proxies.Accordion load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return atlas_designsystem.proxies.Accordion.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Expanded
	 */
	public final java.lang.Boolean getExpanded()
	{
		return getExpanded(getContext());
	}

	/**
	 * @param context
	 * @return value of Expanded
	 */
	public final java.lang.Boolean getExpanded(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Expanded.toString());
	}

	/**
	 * Set value of Expanded
	 * @param expanded
	 */
	public final void setExpanded(java.lang.Boolean expanded)
	{
		setExpanded(getContext(), expanded);
	}

	/**
	 * Set value of Expanded
	 * @param context
	 * @param expanded
	 */
	public final void setExpanded(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean expanded)
	{
		getMendixObject().setValue(context, MemberNames.Expanded.toString(), expanded);
	}

	/**
	 * @return value of ExpandedExpression
	 */
	public final java.lang.Boolean getExpandedExpression()
	{
		return getExpandedExpression(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpandedExpression
	 */
	public final java.lang.Boolean getExpandedExpression(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ExpandedExpression.toString());
	}

	/**
	 * Set value of ExpandedExpression
	 * @param expandedexpression
	 */
	public final void setExpandedExpression(java.lang.Boolean expandedexpression)
	{
		setExpandedExpression(getContext(), expandedexpression);
	}

	/**
	 * Set value of ExpandedExpression
	 * @param context
	 * @param expandedexpression
	 */
	public final void setExpandedExpression(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean expandedexpression)
	{
		getMendixObject().setValue(context, MemberNames.ExpandedExpression.toString(), expandedexpression);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return accordionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final atlas_designsystem.proxies.Accordion that = (atlas_designsystem.proxies.Accordion) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
