// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_designsystem.proxies;

public class CheckBox implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject checkBoxMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Atlas_DesignSystem.CheckBox";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BooleanTrue("BooleanTrue"),
		BooleanFalse("BooleanFalse");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CheckBox(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CheckBox(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject checkBoxMendixObject)
	{
		if (checkBoxMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, checkBoxMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.checkBoxMendixObject = checkBoxMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static atlas_designsystem.proxies.CheckBox initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new atlas_designsystem.proxies.CheckBox(context, mendixObject);
	}

	public static atlas_designsystem.proxies.CheckBox load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return atlas_designsystem.proxies.CheckBox.initialize(context, mendixObject);
	}

	/**
	 * @return value of BooleanTrue
	 */
	public final java.lang.Boolean getBooleanTrue()
	{
		return getBooleanTrue(getContext());
	}

	/**
	 * @param context
	 * @return value of BooleanTrue
	 */
	public final java.lang.Boolean getBooleanTrue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.BooleanTrue.toString());
	}

	/**
	 * Set value of BooleanTrue
	 * @param booleantrue
	 */
	public final void setBooleanTrue(java.lang.Boolean booleantrue)
	{
		setBooleanTrue(getContext(), booleantrue);
	}

	/**
	 * Set value of BooleanTrue
	 * @param context
	 * @param booleantrue
	 */
	public final void setBooleanTrue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean booleantrue)
	{
		getMendixObject().setValue(context, MemberNames.BooleanTrue.toString(), booleantrue);
	}

	/**
	 * @return value of BooleanFalse
	 */
	public final java.lang.Boolean getBooleanFalse()
	{
		return getBooleanFalse(getContext());
	}

	/**
	 * @param context
	 * @return value of BooleanFalse
	 */
	public final java.lang.Boolean getBooleanFalse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.BooleanFalse.toString());
	}

	/**
	 * Set value of BooleanFalse
	 * @param booleanfalse
	 */
	public final void setBooleanFalse(java.lang.Boolean booleanfalse)
	{
		setBooleanFalse(getContext(), booleanfalse);
	}

	/**
	 * Set value of BooleanFalse
	 * @param context
	 * @param booleanfalse
	 */
	public final void setBooleanFalse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean booleanfalse)
	{
		getMendixObject().setValue(context, MemberNames.BooleanFalse.toString(), booleanfalse);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return checkBoxMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final atlas_designsystem.proxies.CheckBox that = (atlas_designsystem.proxies.CheckBox) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
