// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_designsystem.proxies;

public class Dropdown
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dropdownMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Atlas_DesignSystem.Dropdown";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ValueSet("ValueSet"),
		NoValue("NoValue");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Dropdown(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Atlas_DesignSystem.Dropdown"));
	}

	protected Dropdown(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dropdownMendixObject)
	{
		if (dropdownMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Atlas_DesignSystem.Dropdown", dropdownMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Atlas_DesignSystem.Dropdown");

		this.dropdownMendixObject = dropdownMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Dropdown.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static atlas_designsystem.proxies.Dropdown initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return atlas_designsystem.proxies.Dropdown.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static atlas_designsystem.proxies.Dropdown initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new atlas_designsystem.proxies.Dropdown(context, mendixObject);
	}

	public static atlas_designsystem.proxies.Dropdown load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return atlas_designsystem.proxies.Dropdown.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of ValueSet
	 * @param valueset
	 */
	public final atlas_designsystem.proxies.DropdownEnum getValueSet()
	{
		return getValueSet(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueSet
	 */
	public final atlas_designsystem.proxies.DropdownEnum getValueSet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ValueSet.toString());
		if (obj == null)
			return null;

		return atlas_designsystem.proxies.DropdownEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ValueSet
	 * @param valueset
	 */
	public final void setValueSet(atlas_designsystem.proxies.DropdownEnum valueset)
	{
		setValueSet(getContext(), valueset);
	}

	/**
	 * Set value of ValueSet
	 * @param context
	 * @param valueset
	 */
	public final void setValueSet(com.mendix.systemwideinterfaces.core.IContext context, atlas_designsystem.proxies.DropdownEnum valueset)
	{
		if (valueset != null)
			getMendixObject().setValue(context, MemberNames.ValueSet.toString(), valueset.toString());
		else
			getMendixObject().setValue(context, MemberNames.ValueSet.toString(), null);
	}

	/**
	 * Set value of NoValue
	 * @param novalue
	 */
	public final atlas_designsystem.proxies.DropdownEnum getNoValue()
	{
		return getNoValue(getContext());
	}

	/**
	 * @param context
	 * @return value of NoValue
	 */
	public final atlas_designsystem.proxies.DropdownEnum getNoValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.NoValue.toString());
		if (obj == null)
			return null;

		return atlas_designsystem.proxies.DropdownEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of NoValue
	 * @param novalue
	 */
	public final void setNoValue(atlas_designsystem.proxies.DropdownEnum novalue)
	{
		setNoValue(getContext(), novalue);
	}

	/**
	 * Set value of NoValue
	 * @param context
	 * @param novalue
	 */
	public final void setNoValue(com.mendix.systemwideinterfaces.core.IContext context, atlas_designsystem.proxies.DropdownEnum novalue)
	{
		if (novalue != null)
			getMendixObject().setValue(context, MemberNames.NoValue.toString(), novalue.toString());
		else
			getMendixObject().setValue(context, MemberNames.NoValue.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dropdownMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final atlas_designsystem.proxies.Dropdown that = (atlas_designsystem.proxies.Dropdown) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Atlas_DesignSystem.Dropdown";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
