// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_designsystem.proxies;

public class TaskInboxImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Atlas_DesignSystem.TaskInboxImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		TaskInbox_TaskInboxImage("Atlas_DesignSystem.TaskInbox_TaskInboxImage");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TaskInboxImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Atlas_DesignSystem.TaskInboxImage"));
	}

	protected TaskInboxImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject taskInboxImageMendixObject)
	{
		super(context, taskInboxImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Atlas_DesignSystem.TaskInboxImage", taskInboxImageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Atlas_DesignSystem.TaskInboxImage");
	}

	/**
	 * @deprecated Use 'TaskInboxImage.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static atlas_designsystem.proxies.TaskInboxImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return atlas_designsystem.proxies.TaskInboxImage.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static atlas_designsystem.proxies.TaskInboxImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new atlas_designsystem.proxies.TaskInboxImage(context, mendixObject);
	}

	public static atlas_designsystem.proxies.TaskInboxImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return atlas_designsystem.proxies.TaskInboxImage.initialize(context, mendixObject);
	}

	public static java.util.List<atlas_designsystem.proxies.TaskInboxImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<atlas_designsystem.proxies.TaskInboxImage> result = new java.util.ArrayList<atlas_designsystem.proxies.TaskInboxImage>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Atlas_DesignSystem.TaskInboxImage" + xpathConstraint))
			result.add(atlas_designsystem.proxies.TaskInboxImage.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of TaskInbox_TaskInboxImage
	 */
	public final atlas_designsystem.proxies.TaskInbox getTaskInbox_TaskInboxImage() throws com.mendix.core.CoreException
	{
		return getTaskInbox_TaskInboxImage(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskInbox_TaskInboxImage
	 */
	public final atlas_designsystem.proxies.TaskInbox getTaskInbox_TaskInboxImage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		atlas_designsystem.proxies.TaskInbox result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskInbox_TaskInboxImage.toString());
		if (identifier != null)
			result = atlas_designsystem.proxies.TaskInbox.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TaskInbox_TaskInboxImage
	 * @param taskinbox_taskinboximage
	 */
	public final void setTaskInbox_TaskInboxImage(atlas_designsystem.proxies.TaskInbox taskinbox_taskinboximage)
	{
		setTaskInbox_TaskInboxImage(getContext(), taskinbox_taskinboximage);
	}

	/**
	 * Set value of TaskInbox_TaskInboxImage
	 * @param context
	 * @param taskinbox_taskinboximage
	 */
	public final void setTaskInbox_TaskInboxImage(com.mendix.systemwideinterfaces.core.IContext context, atlas_designsystem.proxies.TaskInbox taskinbox_taskinboximage)
	{
		if (taskinbox_taskinboximage == null)
			getMendixObject().setValue(context, MemberNames.TaskInbox_TaskInboxImage.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TaskInbox_TaskInboxImage.toString(), taskinbox_taskinboximage.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final atlas_designsystem.proxies.TaskInboxImage that = (atlas_designsystem.proxies.TaskInboxImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Atlas_DesignSystem.TaskInboxImage";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
