// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_designsystem.proxies;

public class TaskInboxBadges implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject taskInboxBadgesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Atlas_DesignSystem.TaskInboxBadges";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value("Value"),
		TaskInboxBadges_TaskInbox("Atlas_DesignSystem.TaskInboxBadges_TaskInbox");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TaskInboxBadges(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TaskInboxBadges(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject taskInboxBadgesMendixObject)
	{
		if (taskInboxBadgesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, taskInboxBadgesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.taskInboxBadgesMendixObject = taskInboxBadgesMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static atlas_designsystem.proxies.TaskInboxBadges initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new atlas_designsystem.proxies.TaskInboxBadges(context, mendixObject);
	}

	public static atlas_designsystem.proxies.TaskInboxBadges load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return atlas_designsystem.proxies.TaskInboxBadges.initialize(context, mendixObject);
	}

	public static java.util.List<atlas_designsystem.proxies.TaskInboxBadges> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> atlas_designsystem.proxies.TaskInboxBadges.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskInboxBadges_TaskInbox
	 */
	public final atlas_designsystem.proxies.TaskInbox getTaskInboxBadges_TaskInbox() throws com.mendix.core.CoreException
	{
		return getTaskInboxBadges_TaskInbox(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskInboxBadges_TaskInbox
	 * @throws com.mendix.core.CoreException
	 */
	public final atlas_designsystem.proxies.TaskInbox getTaskInboxBadges_TaskInbox(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		atlas_designsystem.proxies.TaskInbox result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskInboxBadges_TaskInbox.toString());
		if (identifier != null) {
			result = atlas_designsystem.proxies.TaskInbox.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskInboxBadges_TaskInbox
	 * @param taskinboxbadges_taskinbox
	 */
	public final void setTaskInboxBadges_TaskInbox(atlas_designsystem.proxies.TaskInbox taskinboxbadges_taskinbox)
	{
		setTaskInboxBadges_TaskInbox(getContext(), taskinboxbadges_taskinbox);
	}

	/**
	 * Set value of TaskInboxBadges_TaskInbox
	 * @param context
	 * @param taskinboxbadges_taskinbox
	 */
	public final void setTaskInboxBadges_TaskInbox(com.mendix.systemwideinterfaces.core.IContext context, atlas_designsystem.proxies.TaskInbox taskinboxbadges_taskinbox)
	{
		if (taskinboxbadges_taskinbox == null) {
			getMendixObject().setValue(context, MemberNames.TaskInboxBadges_TaskInbox.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskInboxBadges_TaskInbox.toString(), taskinboxbadges_taskinbox.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return taskInboxBadgesMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final atlas_designsystem.proxies.TaskInboxBadges that = (atlas_designsystem.proxies.TaskInboxBadges) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
