// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_designsystem.proxies;

public class TaskInboxBadges
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject taskInboxBadgesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Atlas_DesignSystem.TaskInboxBadges";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value("Value"),
		TaskInboxBadges_TaskInbox("Atlas_DesignSystem.TaskInboxBadges_TaskInbox");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TaskInboxBadges(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Atlas_DesignSystem.TaskInboxBadges"));
	}

	protected TaskInboxBadges(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject taskInboxBadgesMendixObject)
	{
		if (taskInboxBadgesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Atlas_DesignSystem.TaskInboxBadges", taskInboxBadgesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Atlas_DesignSystem.TaskInboxBadges");

		this.taskInboxBadgesMendixObject = taskInboxBadgesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TaskInboxBadges.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static atlas_designsystem.proxies.TaskInboxBadges initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return atlas_designsystem.proxies.TaskInboxBadges.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static atlas_designsystem.proxies.TaskInboxBadges initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new atlas_designsystem.proxies.TaskInboxBadges(context, mendixObject);
	}

	public static atlas_designsystem.proxies.TaskInboxBadges load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return atlas_designsystem.proxies.TaskInboxBadges.initialize(context, mendixObject);
	}

	public static java.util.List<atlas_designsystem.proxies.TaskInboxBadges> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<atlas_designsystem.proxies.TaskInboxBadges> result = new java.util.ArrayList<atlas_designsystem.proxies.TaskInboxBadges>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Atlas_DesignSystem.TaskInboxBadges" + xpathConstraint))
			result.add(atlas_designsystem.proxies.TaskInboxBadges.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @return value of TaskInboxBadges_TaskInbox
	 */
	public final atlas_designsystem.proxies.TaskInbox getTaskInboxBadges_TaskInbox() throws com.mendix.core.CoreException
	{
		return getTaskInboxBadges_TaskInbox(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskInboxBadges_TaskInbox
	 */
	public final atlas_designsystem.proxies.TaskInbox getTaskInboxBadges_TaskInbox(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		atlas_designsystem.proxies.TaskInbox result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskInboxBadges_TaskInbox.toString());
		if (identifier != null)
			result = atlas_designsystem.proxies.TaskInbox.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TaskInboxBadges_TaskInbox
	 * @param taskinboxbadges_taskinbox
	 */
	public final void setTaskInboxBadges_TaskInbox(atlas_designsystem.proxies.TaskInbox taskinboxbadges_taskinbox)
	{
		setTaskInboxBadges_TaskInbox(getContext(), taskinboxbadges_taskinbox);
	}

	/**
	 * Set value of TaskInboxBadges_TaskInbox
	 * @param context
	 * @param taskinboxbadges_taskinbox
	 */
	public final void setTaskInboxBadges_TaskInbox(com.mendix.systemwideinterfaces.core.IContext context, atlas_designsystem.proxies.TaskInbox taskinboxbadges_taskinbox)
	{
		if (taskinboxbadges_taskinbox == null)
			getMendixObject().setValue(context, MemberNames.TaskInboxBadges_TaskInbox.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TaskInboxBadges_TaskInbox.toString(), taskinboxbadges_taskinbox.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return taskInboxBadgesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final atlas_designsystem.proxies.TaskInboxBadges that = (atlas_designsystem.proxies.TaskInboxBadges) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Atlas_DesignSystem.TaskInboxBadges";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
