// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_ui_data.proxies;

public class AtlasChartData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject atlasChartDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Atlas_UI_Data.AtlasChartData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DayOfWeek("DayOfWeek"),
		Productivity("Productivity"),
		bubbleSize("bubbleSize"),
		AtlasChartData_AtlasChartSeriesInfo("Atlas_UI_Data.AtlasChartData_AtlasChartSeriesInfo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AtlasChartData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AtlasChartData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject atlasChartDataMendixObject)
	{
		if (atlasChartDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, atlasChartDataMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.atlasChartDataMendixObject = atlasChartDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static atlas_ui_data.proxies.AtlasChartData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new atlas_ui_data.proxies.AtlasChartData(context, mendixObject);
	}

	public static atlas_ui_data.proxies.AtlasChartData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return atlas_ui_data.proxies.AtlasChartData.initialize(context, mendixObject);
	}

	/**
	 * @return value of DayOfWeek
	 */
	public final java.lang.String getDayOfWeek()
	{
		return getDayOfWeek(getContext());
	}

	/**
	 * @param context
	 * @return value of DayOfWeek
	 */
	public final java.lang.String getDayOfWeek(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DayOfWeek.toString());
	}

	/**
	 * Set value of DayOfWeek
	 * @param dayofweek
	 */
	public final void setDayOfWeek(java.lang.String dayofweek)
	{
		setDayOfWeek(getContext(), dayofweek);
	}

	/**
	 * Set value of DayOfWeek
	 * @param context
	 * @param dayofweek
	 */
	public final void setDayOfWeek(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dayofweek)
	{
		getMendixObject().setValue(context, MemberNames.DayOfWeek.toString(), dayofweek);
	}

	/**
	 * @return value of Productivity
	 */
	public final java.lang.Integer getProductivity()
	{
		return getProductivity(getContext());
	}

	/**
	 * @param context
	 * @return value of Productivity
	 */
	public final java.lang.Integer getProductivity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Productivity.toString());
	}

	/**
	 * Set value of Productivity
	 * @param productivity
	 */
	public final void setProductivity(java.lang.Integer productivity)
	{
		setProductivity(getContext(), productivity);
	}

	/**
	 * Set value of Productivity
	 * @param context
	 * @param productivity
	 */
	public final void setProductivity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer productivity)
	{
		getMendixObject().setValue(context, MemberNames.Productivity.toString(), productivity);
	}

	/**
	 * @return value of bubbleSize
	 */
	public final java.lang.Integer getbubbleSize()
	{
		return getbubbleSize(getContext());
	}

	/**
	 * @param context
	 * @return value of bubbleSize
	 */
	public final java.lang.Integer getbubbleSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.bubbleSize.toString());
	}

	/**
	 * Set value of bubbleSize
	 * @param bubblesize
	 */
	public final void setbubbleSize(java.lang.Integer bubblesize)
	{
		setbubbleSize(getContext(), bubblesize);
	}

	/**
	 * Set value of bubbleSize
	 * @param context
	 * @param bubblesize
	 */
	public final void setbubbleSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer bubblesize)
	{
		getMendixObject().setValue(context, MemberNames.bubbleSize.toString(), bubblesize);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AtlasChartData_AtlasChartSeriesInfo
	 */
	public final atlas_ui_data.proxies.AtlasChartSeriesInfo getAtlasChartData_AtlasChartSeriesInfo() throws com.mendix.core.CoreException
	{
		return getAtlasChartData_AtlasChartSeriesInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of AtlasChartData_AtlasChartSeriesInfo
	 * @throws com.mendix.core.CoreException
	 */
	public final atlas_ui_data.proxies.AtlasChartSeriesInfo getAtlasChartData_AtlasChartSeriesInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		atlas_ui_data.proxies.AtlasChartSeriesInfo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AtlasChartData_AtlasChartSeriesInfo.toString());
		if (identifier != null) {
			result = atlas_ui_data.proxies.AtlasChartSeriesInfo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AtlasChartData_AtlasChartSeriesInfo
	 * @param atlaschartdata_atlaschartseriesinfo
	 */
	public final void setAtlasChartData_AtlasChartSeriesInfo(atlas_ui_data.proxies.AtlasChartSeriesInfo atlaschartdata_atlaschartseriesinfo)
	{
		setAtlasChartData_AtlasChartSeriesInfo(getContext(), atlaschartdata_atlaschartseriesinfo);
	}

	/**
	 * Set value of AtlasChartData_AtlasChartSeriesInfo
	 * @param context
	 * @param atlaschartdata_atlaschartseriesinfo
	 */
	public final void setAtlasChartData_AtlasChartSeriesInfo(com.mendix.systemwideinterfaces.core.IContext context, atlas_ui_data.proxies.AtlasChartSeriesInfo atlaschartdata_atlaschartseriesinfo)
	{
		if (atlaschartdata_atlaschartseriesinfo == null) {
			getMendixObject().setValue(context, MemberNames.AtlasChartData_AtlasChartSeriesInfo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AtlasChartData_AtlasChartSeriesInfo.toString(), atlaschartdata_atlaschartseriesinfo.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return atlasChartDataMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final atlas_ui_data.proxies.AtlasChartData that = (atlas_ui_data.proxies.AtlasChartData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
