// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_ui_data.proxies;

public class AtlasGenericObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject atlasGenericObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Atlas_UI_Data.AtlasGenericObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AtlasAutonumber("AtlasAutonumber"),
		AtlasBinary("AtlasBinary"),
		AtlasString("AtlasString"),
		AtlasBoolean("AtlasBoolean"),
		AtlasDateTime("AtlasDateTime"),
		AtlasDecimal("AtlasDecimal"),
		AtlasEnumeration("AtlasEnumeration"),
		AtlasHashedString("AtlasHashedString"),
		AtlasInteger("AtlasInteger"),
		AtlasFloat("AtlasFloat"),
		AtlasLong("AtlasLong"),
		AtlasCurrency("AtlasCurrency"),
		AtlasChecked("AtlasChecked"),
		AtlasSimpleEnum("AtlasSimpleEnum");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AtlasGenericObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Atlas_UI_Data.AtlasGenericObject"));
	}

	protected AtlasGenericObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject atlasGenericObjectMendixObject)
	{
		if (atlasGenericObjectMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Atlas_UI_Data.AtlasGenericObject", atlasGenericObjectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Atlas_UI_Data.AtlasGenericObject");

		this.atlasGenericObjectMendixObject = atlasGenericObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AtlasGenericObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static atlas_ui_data.proxies.AtlasGenericObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return atlas_ui_data.proxies.AtlasGenericObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static atlas_ui_data.proxies.AtlasGenericObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new atlas_ui_data.proxies.AtlasGenericObject(context, mendixObject);
	}

	public static atlas_ui_data.proxies.AtlasGenericObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return atlas_ui_data.proxies.AtlasGenericObject.initialize(context, mendixObject);
	}

	public static java.util.List<atlas_ui_data.proxies.AtlasGenericObject> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<atlas_ui_data.proxies.AtlasGenericObject> result = new java.util.ArrayList<atlas_ui_data.proxies.AtlasGenericObject>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Atlas_UI_Data.AtlasGenericObject" + xpathConstraint))
			result.add(atlas_ui_data.proxies.AtlasGenericObject.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AtlasAutonumber
	 */
	public final java.lang.Long getAtlasAutonumber()
	{
		return getAtlasAutonumber(getContext());
	}

	/**
	 * @param context
	 * @return value of AtlasAutonumber
	 */
	public final java.lang.Long getAtlasAutonumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.AtlasAutonumber.toString());
	}

	/**
	 * Set value of AtlasAutonumber
	 * @param atlasautonumber
	 */
	public final void setAtlasAutonumber(java.lang.Long atlasautonumber)
	{
		setAtlasAutonumber(getContext(), atlasautonumber);
	}

	/**
	 * Set value of AtlasAutonumber
	 * @param context
	 * @param atlasautonumber
	 */
	public final void setAtlasAutonumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long atlasautonumber)
	{
		getMendixObject().setValue(context, MemberNames.AtlasAutonumber.toString(), atlasautonumber);
	}

	/**
	  * The contents of the binary field will be written to the output stream.
	  * The output stream will be closed at the end.
	  *
	  * @param context
	  * @param outputStream
	  */
	public final void getAtlasBinary(com.mendix.systemwideinterfaces.core.IContext context, java.io.OutputStream outputStream)
	{
		com.mendix.core.objectmanagement.member.MendixBinary binary = (com.mendix.core.objectmanagement.member.MendixBinary) getMendixObject().getMember(context, MemberNames.AtlasBinary.toString());
		binary.retrieveValue(context, outputStream);
	}

	/**
	  * Stores the bytes from the given InputStream.
	  *
	  * Please note that the input stream will be immediately sent to the data store,
	  * whether you commit the Mendix object or not.
	  *
	  * @param context
	  * @param inputStream
	  * @param length the number of bytes in the stream
	  */
	public final void setAtlasBinary(com.mendix.systemwideinterfaces.core.IContext context, java.io.InputStream inputStream, long length)
	{
		if (getMendixObject().getState() == com.mendix.systemwideinterfaces.core.IMendixObject.ObjectState.INSTANTIATED)
			try { commit(); } catch (com.mendix.core.CoreException ex) { }
		com.mendix.core.objectmanagement.member.MendixBinary binary = (com.mendix.core.objectmanagement.member.MendixBinary) getMendixObject().getMember(context, MemberNames.AtlasBinary.toString());
		binary.storeValue(context, inputStream, length);
	}

	/**
	 * @return value of AtlasString
	 */
	public final java.lang.String getAtlasString()
	{
		return getAtlasString(getContext());
	}

	/**
	 * @param context
	 * @return value of AtlasString
	 */
	public final java.lang.String getAtlasString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AtlasString.toString());
	}

	/**
	 * Set value of AtlasString
	 * @param atlasstring
	 */
	public final void setAtlasString(java.lang.String atlasstring)
	{
		setAtlasString(getContext(), atlasstring);
	}

	/**
	 * Set value of AtlasString
	 * @param context
	 * @param atlasstring
	 */
	public final void setAtlasString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String atlasstring)
	{
		getMendixObject().setValue(context, MemberNames.AtlasString.toString(), atlasstring);
	}

	/**
	 * @return value of AtlasBoolean
	 */
	public final java.lang.Boolean getAtlasBoolean()
	{
		return getAtlasBoolean(getContext());
	}

	/**
	 * @param context
	 * @return value of AtlasBoolean
	 */
	public final java.lang.Boolean getAtlasBoolean(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AtlasBoolean.toString());
	}

	/**
	 * Set value of AtlasBoolean
	 * @param atlasboolean
	 */
	public final void setAtlasBoolean(java.lang.Boolean atlasboolean)
	{
		setAtlasBoolean(getContext(), atlasboolean);
	}

	/**
	 * Set value of AtlasBoolean
	 * @param context
	 * @param atlasboolean
	 */
	public final void setAtlasBoolean(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean atlasboolean)
	{
		getMendixObject().setValue(context, MemberNames.AtlasBoolean.toString(), atlasboolean);
	}

	/**
	 * @return value of AtlasDateTime
	 */
	public final java.util.Date getAtlasDateTime()
	{
		return getAtlasDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of AtlasDateTime
	 */
	public final java.util.Date getAtlasDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.AtlasDateTime.toString());
	}

	/**
	 * Set value of AtlasDateTime
	 * @param atlasdatetime
	 */
	public final void setAtlasDateTime(java.util.Date atlasdatetime)
	{
		setAtlasDateTime(getContext(), atlasdatetime);
	}

	/**
	 * Set value of AtlasDateTime
	 * @param context
	 * @param atlasdatetime
	 */
	public final void setAtlasDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date atlasdatetime)
	{
		getMendixObject().setValue(context, MemberNames.AtlasDateTime.toString(), atlasdatetime);
	}

	/**
	 * @return value of AtlasDecimal
	 */
	public final java.math.BigDecimal getAtlasDecimal()
	{
		return getAtlasDecimal(getContext());
	}

	/**
	 * @param context
	 * @return value of AtlasDecimal
	 */
	public final java.math.BigDecimal getAtlasDecimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AtlasDecimal.toString());
	}

	/**
	 * Set value of AtlasDecimal
	 * @param atlasdecimal
	 */
	public final void setAtlasDecimal(java.math.BigDecimal atlasdecimal)
	{
		setAtlasDecimal(getContext(), atlasdecimal);
	}

	/**
	 * Set value of AtlasDecimal
	 * @param context
	 * @param atlasdecimal
	 */
	public final void setAtlasDecimal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal atlasdecimal)
	{
		getMendixObject().setValue(context, MemberNames.AtlasDecimal.toString(), atlasdecimal);
	}

	/**
	 * Set value of AtlasEnumeration
	 * @param atlasenumeration
	 */
	public final atlas_ui_data.proxies.DefaultEnumeration getAtlasEnumeration()
	{
		return getAtlasEnumeration(getContext());
	}

	/**
	 * @param context
	 * @return value of AtlasEnumeration
	 */
	public final atlas_ui_data.proxies.DefaultEnumeration getAtlasEnumeration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AtlasEnumeration.toString());
		if (obj == null)
			return null;

		return atlas_ui_data.proxies.DefaultEnumeration.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AtlasEnumeration
	 * @param atlasenumeration
	 */
	public final void setAtlasEnumeration(atlas_ui_data.proxies.DefaultEnumeration atlasenumeration)
	{
		setAtlasEnumeration(getContext(), atlasenumeration);
	}

	/**
	 * Set value of AtlasEnumeration
	 * @param context
	 * @param atlasenumeration
	 */
	public final void setAtlasEnumeration(com.mendix.systemwideinterfaces.core.IContext context, atlas_ui_data.proxies.DefaultEnumeration atlasenumeration)
	{
		if (atlasenumeration != null)
			getMendixObject().setValue(context, MemberNames.AtlasEnumeration.toString(), atlasenumeration.toString());
		else
			getMendixObject().setValue(context, MemberNames.AtlasEnumeration.toString(), null);
	}

	/**
	 * Set value of AtlasHashedString
	 * @param atlashashedstring
	 */
	public final void setAtlasHashedString(java.lang.String atlashashedstring)
	{
		setAtlasHashedString(getContext(), atlashashedstring);
	}

	/**
	 * Set value of AtlasHashedString
	 * @param context
	 * @param atlashashedstring
	 */
	public final void setAtlasHashedString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String atlashashedstring)
	{
		getMendixObject().setValue(context, MemberNames.AtlasHashedString.toString(), atlashashedstring);
	}

	/**
	 * @return value of AtlasInteger
	 */
	public final java.lang.Integer getAtlasInteger()
	{
		return getAtlasInteger(getContext());
	}

	/**
	 * @param context
	 * @return value of AtlasInteger
	 */
	public final java.lang.Integer getAtlasInteger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AtlasInteger.toString());
	}

	/**
	 * Set value of AtlasInteger
	 * @param atlasinteger
	 */
	public final void setAtlasInteger(java.lang.Integer atlasinteger)
	{
		setAtlasInteger(getContext(), atlasinteger);
	}

	/**
	 * Set value of AtlasInteger
	 * @param context
	 * @param atlasinteger
	 */
	public final void setAtlasInteger(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer atlasinteger)
	{
		getMendixObject().setValue(context, MemberNames.AtlasInteger.toString(), atlasinteger);
	}

	/**
	 * @return value of AtlasFloat
	 */
	public final java.math.BigDecimal getAtlasFloat()
	{
		return getAtlasFloat(getContext());
	}

	/**
	 * @param context
	 * @return value of AtlasFloat
	 */
	public final java.math.BigDecimal getAtlasFloat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AtlasFloat.toString());
	}

	/**
	 * Set value of AtlasFloat
	 * @param atlasfloat
	 */
	public final void setAtlasFloat(java.math.BigDecimal atlasfloat)
	{
		setAtlasFloat(getContext(), atlasfloat);
	}

	/**
	 * Set value of AtlasFloat
	 * @param context
	 * @param atlasfloat
	 */
	public final void setAtlasFloat(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal atlasfloat)
	{
		getMendixObject().setValue(context, MemberNames.AtlasFloat.toString(), atlasfloat);
	}

	/**
	 * @return value of AtlasLong
	 */
	public final java.lang.Long getAtlasLong()
	{
		return getAtlasLong(getContext());
	}

	/**
	 * @param context
	 * @return value of AtlasLong
	 */
	public final java.lang.Long getAtlasLong(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.AtlasLong.toString());
	}

	/**
	 * Set value of AtlasLong
	 * @param atlaslong
	 */
	public final void setAtlasLong(java.lang.Long atlaslong)
	{
		setAtlasLong(getContext(), atlaslong);
	}

	/**
	 * Set value of AtlasLong
	 * @param context
	 * @param atlaslong
	 */
	public final void setAtlasLong(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long atlaslong)
	{
		getMendixObject().setValue(context, MemberNames.AtlasLong.toString(), atlaslong);
	}

	/**
	 * @return value of AtlasCurrency
	 */
	public final java.math.BigDecimal getAtlasCurrency()
	{
		return getAtlasCurrency(getContext());
	}

	/**
	 * @param context
	 * @return value of AtlasCurrency
	 */
	public final java.math.BigDecimal getAtlasCurrency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AtlasCurrency.toString());
	}

	/**
	 * Set value of AtlasCurrency
	 * @param atlascurrency
	 */
	public final void setAtlasCurrency(java.math.BigDecimal atlascurrency)
	{
		setAtlasCurrency(getContext(), atlascurrency);
	}

	/**
	 * Set value of AtlasCurrency
	 * @param context
	 * @param atlascurrency
	 */
	public final void setAtlasCurrency(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal atlascurrency)
	{
		getMendixObject().setValue(context, MemberNames.AtlasCurrency.toString(), atlascurrency);
	}

	/**
	 * @return value of AtlasChecked
	 */
	public final java.lang.Boolean getAtlasChecked()
	{
		return getAtlasChecked(getContext());
	}

	/**
	 * @param context
	 * @return value of AtlasChecked
	 */
	public final java.lang.Boolean getAtlasChecked(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AtlasChecked.toString());
	}

	/**
	 * Set value of AtlasChecked
	 * @param atlaschecked
	 */
	public final void setAtlasChecked(java.lang.Boolean atlaschecked)
	{
		setAtlasChecked(getContext(), atlaschecked);
	}

	/**
	 * Set value of AtlasChecked
	 * @param context
	 * @param atlaschecked
	 */
	public final void setAtlasChecked(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean atlaschecked)
	{
		getMendixObject().setValue(context, MemberNames.AtlasChecked.toString(), atlaschecked);
	}

	/**
	 * Set value of AtlasSimpleEnum
	 * @param atlassimpleenum
	 */
	public final atlas_ui_data.proxies.SimpleEnum getAtlasSimpleEnum()
	{
		return getAtlasSimpleEnum(getContext());
	}

	/**
	 * @param context
	 * @return value of AtlasSimpleEnum
	 */
	public final atlas_ui_data.proxies.SimpleEnum getAtlasSimpleEnum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AtlasSimpleEnum.toString());
		if (obj == null)
			return null;

		return atlas_ui_data.proxies.SimpleEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AtlasSimpleEnum
	 * @param atlassimpleenum
	 */
	public final void setAtlasSimpleEnum(atlas_ui_data.proxies.SimpleEnum atlassimpleenum)
	{
		setAtlasSimpleEnum(getContext(), atlassimpleenum);
	}

	/**
	 * Set value of AtlasSimpleEnum
	 * @param context
	 * @param atlassimpleenum
	 */
	public final void setAtlasSimpleEnum(com.mendix.systemwideinterfaces.core.IContext context, atlas_ui_data.proxies.SimpleEnum atlassimpleenum)
	{
		if (atlassimpleenum != null)
			getMendixObject().setValue(context, MemberNames.AtlasSimpleEnum.toString(), atlassimpleenum.toString());
		else
			getMendixObject().setValue(context, MemberNames.AtlasSimpleEnum.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return atlasGenericObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final atlas_ui_data.proxies.AtlasGenericObject that = (atlas_ui_data.proxies.AtlasGenericObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Atlas_UI_Data.AtlasGenericObject";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
