// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_ui_data.proxies;

public enum Departments
{
	Marketing(new java.lang.String[][] { new java.lang.String[] { "en_US", "Marketing" } }),
	Sales(new java.lang.String[][] { new java.lang.String[] { "en_US", "Sales" } }),
	RnD(new java.lang.String[][] { new java.lang.String[] { "en_US", "RnD" } }),
	Finance(new java.lang.String[][] { new java.lang.String[] { "en_US", "Finance" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Departments(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
