// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_ui_data.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Atlas_UI_Data module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_AtlasCountryBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.DS_AtlasCountry");
		return builder;
	}

	public static atlas_ui_data.proxies.AtlasCountry dS_AtlasCountry(IContext context)
	{
		Object result = dS_AtlasCountryBuilder().execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasCountry.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_CreateAtlasChartDataBuilder(
		atlas_ui_data.proxies.AtlasStatistics _atlasStatistics
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.DS_CreateAtlasChartData");
		builder = builder.withParam("AtlasStatistics", _atlasStatistics);
		return builder;
	}

	public static java.util.List<atlas_ui_data.proxies.AtlasChartData> dS_CreateAtlasChartData(
		IContext context,
		atlas_ui_data.proxies.AtlasStatistics _atlasStatistics
	)
	{
		Object result = dS_CreateAtlasChartDataBuilder(
				_atlasStatistics
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> atlas_ui_data.proxies.AtlasChartData.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_DuplicateGenericObjectBuilder(
		atlas_ui_data.proxies.AtlasGenericObject _defaultObject
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.DS_DuplicateGenericObject");
		builder = builder.withParam("DefaultObject", _defaultObject);
		return builder;
	}

	public static atlas_ui_data.proxies.AtlasGenericObject dS_DuplicateGenericObject(
		IContext context,
		atlas_ui_data.proxies.AtlasGenericObject _defaultObject
	)
	{
		Object result = dS_DuplicateGenericObjectBuilder(
				_defaultObject
			)
			.execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasGenericObject.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_DuplicateLocationDateBuilder(
		atlas_ui_data.proxies.AtlasLocationDate _locationDateObjectParam
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.DS_DuplicateLocationDate");
		builder = builder.withParam("LocationDateObjectParam", _locationDateObjectParam);
		return builder;
	}

	public static atlas_ui_data.proxies.AtlasLocationDate dS_DuplicateLocationDate(
		IContext context,
		atlas_ui_data.proxies.AtlasLocationDate _locationDateObjectParam
	)
	{
		Object result = dS_DuplicateLocationDateBuilder(
				_locationDateObjectParam
			)
			.execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasLocationDate.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_DuplicatePeopleBuilder(
		atlas_ui_data.proxies.AtlasPeople _atlasUserParam
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.DS_DuplicatePeople");
		builder = builder.withParam("AtlasUserParam", _atlasUserParam);
		return builder;
	}

	public static atlas_ui_data.proxies.AtlasPeople dS_DuplicatePeople(
		IContext context,
		atlas_ui_data.proxies.AtlasPeople _atlasUserParam
	)
	{
		Object result = dS_DuplicatePeopleBuilder(
				_atlasUserParam
			)
			.execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasPeople.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_DuplicateStatisticBuilder(
		atlas_ui_data.proxies.AtlasStatistics _atlasStatisticsParam
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.DS_DuplicateStatistic");
		builder = builder.withParam("AtlasStatisticsParam", _atlasStatisticsParam);
		return builder;
	}

	public static atlas_ui_data.proxies.AtlasStatistics dS_DuplicateStatistic(
		IContext context,
		atlas_ui_data.proxies.AtlasStatistics _atlasStatisticsParam
	)
	{
		Object result = dS_DuplicateStatisticBuilder(
				_atlasStatisticsParam
			)
			.execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasStatistics.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_EmptyGenericObjectBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.DS_EmptyGenericObject");
		return builder;
	}

	public static atlas_ui_data.proxies.AtlasGenericObject dS_EmptyGenericObject(IContext context)
	{
		Object result = dS_EmptyGenericObjectBuilder().execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasGenericObject.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_GetFirstGenericObjectBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.IVK_GetFirstGenericObject");
		return builder;
	}

	public static atlas_ui_data.proxies.AtlasGenericObject iVK_GetFirstGenericObject(IContext context)
	{
		Object result = iVK_GetFirstGenericObjectBuilder().execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasGenericObject.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_GetFirstLocationDateObjectBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.IVK_GetFirstLocationDateObject");
		return builder;
	}

	public static atlas_ui_data.proxies.AtlasLocationDate iVK_GetFirstLocationDateObject(IContext context)
	{
		Object result = iVK_GetFirstLocationDateObjectBuilder().execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasLocationDate.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_GetFirstPeopleObjectBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.IVK_GetFirstPeopleObject");
		return builder;
	}

	public static atlas_ui_data.proxies.AtlasPeople iVK_GetFirstPeopleObject(IContext context)
	{
		Object result = iVK_GetFirstPeopleObjectBuilder().execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasPeople.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_GetFirstStatisticObjectBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.IVK_GetFirstStatisticObject");
		return builder;
	}

	public static atlas_ui_data.proxies.AtlasStatistics iVK_GetFirstStatisticObject(IContext context)
	{
		Object result = iVK_GetFirstStatisticObjectBuilder().execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasStatistics.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_RetrieveAllLocationDateObjectsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.IVK_RetrieveAllLocationDateObjects");
		return builder;
	}

	public static java.util.List<atlas_ui_data.proxies.AtlasLocationDate> iVK_RetrieveAllLocationDateObjects(IContext context)
	{
		Object result = iVK_RetrieveAllLocationDateObjectsBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> atlas_ui_data.proxies.AtlasLocationDate.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_RetrieveAllPeopleObjectsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.IVK_RetrieveAllPeopleObjects");
		return builder;
	}

	public static java.util.List<atlas_ui_data.proxies.AtlasPeople> iVK_RetrieveAllPeopleObjects(IContext context)
	{
		Object result = iVK_RetrieveAllPeopleObjectsBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> atlas_ui_data.proxies.AtlasPeople.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder iVK_RetrieveAllStatisticObjectsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.IVK_RetrieveAllStatisticObjects");
		return builder;
	}

	public static java.util.List<atlas_ui_data.proxies.AtlasStatistics> iVK_RetrieveAllStatisticObjects(IContext context)
	{
		Object result = iVK_RetrieveAllStatisticObjectsBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> atlas_ui_data.proxies.AtlasStatistics.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_Parse_DecimalBuilder(
		java.lang.String _atlasString
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.MF_Parse_Decimal");
		builder = builder.withParam("AtlasString", _atlasString);
		return builder;
	}

	public static java.math.BigDecimal mF_Parse_Decimal(
		IContext context,
		java.lang.String _atlasString
	)
	{
		Object result = mF_Parse_DecimalBuilder(
				_atlasString
			)
			.execute(context);
		return (java.math.BigDecimal) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_Parse_DTBuilder(
		java.lang.Long _atlasDateTime
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.MF_Parse_DT");
		builder = builder.withParam("AtlasDateTime", _atlasDateTime);
		return builder;
	}

	public static java.util.Date mF_Parse_DT(
		IContext context,
		java.lang.Long _atlasDateTime
	)
	{
		Object result = mF_Parse_DTBuilder(
				_atlasDateTime
			)
			.execute(context);
		return (java.util.Date) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_Parse_EnumBuilder(
		java.lang.String _atlasEnumeration
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.MF_Parse_Enum");
		builder = builder.withParam("AtlasEnumeration", _atlasEnumeration);
		return builder;
	}

	public static atlas_ui_data.proxies.DefaultEnumeration mF_Parse_Enum(
		IContext context,
		java.lang.String _atlasEnumeration
	)
	{
		Object result = mF_Parse_EnumBuilder(
				_atlasEnumeration
			)
			.execute(context);
		return result == null ? null : atlas_ui_data.proxies.DefaultEnumeration.valueOf((java.lang.String) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_Parse_IntergerBuilder(
		java.lang.String _atlasInteger
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_UI_Data.MF_Parse_Interger");
		builder = builder.withParam("AtlasInteger", _atlasInteger);
		return builder;
	}

	public static java.lang.Long mF_Parse_Interger(
		IContext context,
		java.lang.String _atlasInteger
	)
	{
		Object result = mF_Parse_IntergerBuilder(
				_atlasInteger
			)
			.execute(context);
		return (java.lang.Long) result;
	}
}
