// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public class DeviceInfo
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject deviceInfoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeMobileResources.DeviceInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ApplicationName("ApplicationName"),
		BatteryLevel("BatteryLevel"),
		Brand("Brand"),
		BuildNumber("BuildNumber"),
		BundleId("BundleId"),
		Carrier("Carrier"),
		DeviceCountry("DeviceCountry"),
		DeviceId("DeviceId"),
		DeviceLocale("DeviceLocale"),
		FontScale("FontScale"),
		FreeDiskStorage("FreeDiskStorage"),
		Manufacturer("Manufacturer"),
		Model("Model"),
		ReadableVersion("ReadableVersion"),
		SystemName("SystemName"),
		SystemVersion("SystemVersion"),
		Timezone("Timezone"),
		TotalDiskCapacity("TotalDiskCapacity"),
		TotalMemory("TotalMemory"),
		UniqueId("UniqueId"),
		UserAgent("UserAgent"),
		Version("Version"),
		Is24Hour("Is24Hour"),
		IsEmulator("IsEmulator"),
		IsTablet("IsTablet"),
		IsLandscape("IsLandscape"),
		HasNotch("HasNotch");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DeviceInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "NativeMobileResources.DeviceInfo"));
	}

	protected DeviceInfo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject deviceInfoMendixObject)
	{
		if (deviceInfoMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("NativeMobileResources.DeviceInfo", deviceInfoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a NativeMobileResources.DeviceInfo");

		this.deviceInfoMendixObject = deviceInfoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DeviceInfo.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static nativemobileresources.proxies.DeviceInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nativemobileresources.proxies.DeviceInfo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static nativemobileresources.proxies.DeviceInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativemobileresources.proxies.DeviceInfo(context, mendixObject);
	}

	public static nativemobileresources.proxies.DeviceInfo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativemobileresources.proxies.DeviceInfo.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ApplicationName
	 */
	public final java.lang.String getApplicationName()
	{
		return getApplicationName(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicationName
	 */
	public final java.lang.String getApplicationName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApplicationName.toString());
	}

	/**
	 * Set value of ApplicationName
	 * @param applicationname
	 */
	public final void setApplicationName(java.lang.String applicationname)
	{
		setApplicationName(getContext(), applicationname);
	}

	/**
	 * Set value of ApplicationName
	 * @param context
	 * @param applicationname
	 */
	public final void setApplicationName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String applicationname)
	{
		getMendixObject().setValue(context, MemberNames.ApplicationName.toString(), applicationname);
	}

	/**
	 * @return value of BatteryLevel
	 */
	public final java.math.BigDecimal getBatteryLevel()
	{
		return getBatteryLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of BatteryLevel
	 */
	public final java.math.BigDecimal getBatteryLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.BatteryLevel.toString());
	}

	/**
	 * Set value of BatteryLevel
	 * @param batterylevel
	 */
	public final void setBatteryLevel(java.math.BigDecimal batterylevel)
	{
		setBatteryLevel(getContext(), batterylevel);
	}

	/**
	 * Set value of BatteryLevel
	 * @param context
	 * @param batterylevel
	 */
	public final void setBatteryLevel(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal batterylevel)
	{
		getMendixObject().setValue(context, MemberNames.BatteryLevel.toString(), batterylevel);
	}

	/**
	 * @return value of Brand
	 */
	public final java.lang.String getBrand()
	{
		return getBrand(getContext());
	}

	/**
	 * @param context
	 * @return value of Brand
	 */
	public final java.lang.String getBrand(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Brand.toString());
	}

	/**
	 * Set value of Brand
	 * @param brand
	 */
	public final void setBrand(java.lang.String brand)
	{
		setBrand(getContext(), brand);
	}

	/**
	 * Set value of Brand
	 * @param context
	 * @param brand
	 */
	public final void setBrand(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String brand)
	{
		getMendixObject().setValue(context, MemberNames.Brand.toString(), brand);
	}

	/**
	 * @return value of BuildNumber
	 */
	public final java.lang.String getBuildNumber()
	{
		return getBuildNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of BuildNumber
	 */
	public final java.lang.String getBuildNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BuildNumber.toString());
	}

	/**
	 * Set value of BuildNumber
	 * @param buildnumber
	 */
	public final void setBuildNumber(java.lang.String buildnumber)
	{
		setBuildNumber(getContext(), buildnumber);
	}

	/**
	 * Set value of BuildNumber
	 * @param context
	 * @param buildnumber
	 */
	public final void setBuildNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String buildnumber)
	{
		getMendixObject().setValue(context, MemberNames.BuildNumber.toString(), buildnumber);
	}

	/**
	 * @return value of BundleId
	 */
	public final java.lang.String getBundleId()
	{
		return getBundleId(getContext());
	}

	/**
	 * @param context
	 * @return value of BundleId
	 */
	public final java.lang.String getBundleId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BundleId.toString());
	}

	/**
	 * Set value of BundleId
	 * @param bundleid
	 */
	public final void setBundleId(java.lang.String bundleid)
	{
		setBundleId(getContext(), bundleid);
	}

	/**
	 * Set value of BundleId
	 * @param context
	 * @param bundleid
	 */
	public final void setBundleId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bundleid)
	{
		getMendixObject().setValue(context, MemberNames.BundleId.toString(), bundleid);
	}

	/**
	 * @return value of Carrier
	 */
	public final java.lang.String getCarrier()
	{
		return getCarrier(getContext());
	}

	/**
	 * @param context
	 * @return value of Carrier
	 */
	public final java.lang.String getCarrier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Carrier.toString());
	}

	/**
	 * Set value of Carrier
	 * @param carrier
	 */
	public final void setCarrier(java.lang.String carrier)
	{
		setCarrier(getContext(), carrier);
	}

	/**
	 * Set value of Carrier
	 * @param context
	 * @param carrier
	 */
	public final void setCarrier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String carrier)
	{
		getMendixObject().setValue(context, MemberNames.Carrier.toString(), carrier);
	}

	/**
	 * @return value of DeviceCountry
	 */
	public final java.lang.String getDeviceCountry()
	{
		return getDeviceCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of DeviceCountry
	 */
	public final java.lang.String getDeviceCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeviceCountry.toString());
	}

	/**
	 * Set value of DeviceCountry
	 * @param devicecountry
	 */
	public final void setDeviceCountry(java.lang.String devicecountry)
	{
		setDeviceCountry(getContext(), devicecountry);
	}

	/**
	 * Set value of DeviceCountry
	 * @param context
	 * @param devicecountry
	 */
	public final void setDeviceCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String devicecountry)
	{
		getMendixObject().setValue(context, MemberNames.DeviceCountry.toString(), devicecountry);
	}

	/**
	 * @return value of DeviceId
	 */
	public final java.lang.String getDeviceId()
	{
		return getDeviceId(getContext());
	}

	/**
	 * @param context
	 * @return value of DeviceId
	 */
	public final java.lang.String getDeviceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeviceId.toString());
	}

	/**
	 * Set value of DeviceId
	 * @param deviceid
	 */
	public final void setDeviceId(java.lang.String deviceid)
	{
		setDeviceId(getContext(), deviceid);
	}

	/**
	 * Set value of DeviceId
	 * @param context
	 * @param deviceid
	 */
	public final void setDeviceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deviceid)
	{
		getMendixObject().setValue(context, MemberNames.DeviceId.toString(), deviceid);
	}

	/**
	 * @return value of DeviceLocale
	 */
	public final java.lang.String getDeviceLocale()
	{
		return getDeviceLocale(getContext());
	}

	/**
	 * @param context
	 * @return value of DeviceLocale
	 */
	public final java.lang.String getDeviceLocale(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeviceLocale.toString());
	}

	/**
	 * Set value of DeviceLocale
	 * @param devicelocale
	 */
	public final void setDeviceLocale(java.lang.String devicelocale)
	{
		setDeviceLocale(getContext(), devicelocale);
	}

	/**
	 * Set value of DeviceLocale
	 * @param context
	 * @param devicelocale
	 */
	public final void setDeviceLocale(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String devicelocale)
	{
		getMendixObject().setValue(context, MemberNames.DeviceLocale.toString(), devicelocale);
	}

	/**
	 * @return value of FontScale
	 */
	public final java.math.BigDecimal getFontScale()
	{
		return getFontScale(getContext());
	}

	/**
	 * @param context
	 * @return value of FontScale
	 */
	public final java.math.BigDecimal getFontScale(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.FontScale.toString());
	}

	/**
	 * Set value of FontScale
	 * @param fontscale
	 */
	public final void setFontScale(java.math.BigDecimal fontscale)
	{
		setFontScale(getContext(), fontscale);
	}

	/**
	 * Set value of FontScale
	 * @param context
	 * @param fontscale
	 */
	public final void setFontScale(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal fontscale)
	{
		getMendixObject().setValue(context, MemberNames.FontScale.toString(), fontscale);
	}

	/**
	 * @return value of FreeDiskStorage
	 */
	public final java.lang.Long getFreeDiskStorage()
	{
		return getFreeDiskStorage(getContext());
	}

	/**
	 * @param context
	 * @return value of FreeDiskStorage
	 */
	public final java.lang.Long getFreeDiskStorage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.FreeDiskStorage.toString());
	}

	/**
	 * Set value of FreeDiskStorage
	 * @param freediskstorage
	 */
	public final void setFreeDiskStorage(java.lang.Long freediskstorage)
	{
		setFreeDiskStorage(getContext(), freediskstorage);
	}

	/**
	 * Set value of FreeDiskStorage
	 * @param context
	 * @param freediskstorage
	 */
	public final void setFreeDiskStorage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long freediskstorage)
	{
		getMendixObject().setValue(context, MemberNames.FreeDiskStorage.toString(), freediskstorage);
	}

	/**
	 * @return value of Manufacturer
	 */
	public final java.lang.String getManufacturer()
	{
		return getManufacturer(getContext());
	}

	/**
	 * @param context
	 * @return value of Manufacturer
	 */
	public final java.lang.String getManufacturer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Manufacturer.toString());
	}

	/**
	 * Set value of Manufacturer
	 * @param manufacturer
	 */
	public final void setManufacturer(java.lang.String manufacturer)
	{
		setManufacturer(getContext(), manufacturer);
	}

	/**
	 * Set value of Manufacturer
	 * @param context
	 * @param manufacturer
	 */
	public final void setManufacturer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String manufacturer)
	{
		getMendixObject().setValue(context, MemberNames.Manufacturer.toString(), manufacturer);
	}

	/**
	 * @return value of Model
	 */
	public final java.lang.String getModel()
	{
		return getModel(getContext());
	}

	/**
	 * @param context
	 * @return value of Model
	 */
	public final java.lang.String getModel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Model.toString());
	}

	/**
	 * Set value of Model
	 * @param model
	 */
	public final void setModel(java.lang.String model)
	{
		setModel(getContext(), model);
	}

	/**
	 * Set value of Model
	 * @param context
	 * @param model
	 */
	public final void setModel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String model)
	{
		getMendixObject().setValue(context, MemberNames.Model.toString(), model);
	}

	/**
	 * @return value of ReadableVersion
	 */
	public final java.lang.String getReadableVersion()
	{
		return getReadableVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of ReadableVersion
	 */
	public final java.lang.String getReadableVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReadableVersion.toString());
	}

	/**
	 * Set value of ReadableVersion
	 * @param readableversion
	 */
	public final void setReadableVersion(java.lang.String readableversion)
	{
		setReadableVersion(getContext(), readableversion);
	}

	/**
	 * Set value of ReadableVersion
	 * @param context
	 * @param readableversion
	 */
	public final void setReadableVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String readableversion)
	{
		getMendixObject().setValue(context, MemberNames.ReadableVersion.toString(), readableversion);
	}

	/**
	 * @return value of SystemName
	 */
	public final java.lang.String getSystemName()
	{
		return getSystemName(getContext());
	}

	/**
	 * @param context
	 * @return value of SystemName
	 */
	public final java.lang.String getSystemName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SystemName.toString());
	}

	/**
	 * Set value of SystemName
	 * @param systemname
	 */
	public final void setSystemName(java.lang.String systemname)
	{
		setSystemName(getContext(), systemname);
	}

	/**
	 * Set value of SystemName
	 * @param context
	 * @param systemname
	 */
	public final void setSystemName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String systemname)
	{
		getMendixObject().setValue(context, MemberNames.SystemName.toString(), systemname);
	}

	/**
	 * @return value of SystemVersion
	 */
	public final java.lang.String getSystemVersion()
	{
		return getSystemVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of SystemVersion
	 */
	public final java.lang.String getSystemVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SystemVersion.toString());
	}

	/**
	 * Set value of SystemVersion
	 * @param systemversion
	 */
	public final void setSystemVersion(java.lang.String systemversion)
	{
		setSystemVersion(getContext(), systemversion);
	}

	/**
	 * Set value of SystemVersion
	 * @param context
	 * @param systemversion
	 */
	public final void setSystemVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String systemversion)
	{
		getMendixObject().setValue(context, MemberNames.SystemVersion.toString(), systemversion);
	}

	/**
	 * @return value of Timezone
	 */
	public final java.lang.String getTimezone()
	{
		return getTimezone(getContext());
	}

	/**
	 * @param context
	 * @return value of Timezone
	 */
	public final java.lang.String getTimezone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Timezone.toString());
	}

	/**
	 * Set value of Timezone
	 * @param timezone
	 */
	public final void setTimezone(java.lang.String timezone)
	{
		setTimezone(getContext(), timezone);
	}

	/**
	 * Set value of Timezone
	 * @param context
	 * @param timezone
	 */
	public final void setTimezone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timezone)
	{
		getMendixObject().setValue(context, MemberNames.Timezone.toString(), timezone);
	}

	/**
	 * @return value of TotalDiskCapacity
	 */
	public final java.lang.Long getTotalDiskCapacity()
	{
		return getTotalDiskCapacity(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalDiskCapacity
	 */
	public final java.lang.Long getTotalDiskCapacity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.TotalDiskCapacity.toString());
	}

	/**
	 * Set value of TotalDiskCapacity
	 * @param totaldiskcapacity
	 */
	public final void setTotalDiskCapacity(java.lang.Long totaldiskcapacity)
	{
		setTotalDiskCapacity(getContext(), totaldiskcapacity);
	}

	/**
	 * Set value of TotalDiskCapacity
	 * @param context
	 * @param totaldiskcapacity
	 */
	public final void setTotalDiskCapacity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long totaldiskcapacity)
	{
		getMendixObject().setValue(context, MemberNames.TotalDiskCapacity.toString(), totaldiskcapacity);
	}

	/**
	 * @return value of TotalMemory
	 */
	public final java.lang.Long getTotalMemory()
	{
		return getTotalMemory(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalMemory
	 */
	public final java.lang.Long getTotalMemory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.TotalMemory.toString());
	}

	/**
	 * Set value of TotalMemory
	 * @param totalmemory
	 */
	public final void setTotalMemory(java.lang.Long totalmemory)
	{
		setTotalMemory(getContext(), totalmemory);
	}

	/**
	 * Set value of TotalMemory
	 * @param context
	 * @param totalmemory
	 */
	public final void setTotalMemory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long totalmemory)
	{
		getMendixObject().setValue(context, MemberNames.TotalMemory.toString(), totalmemory);
	}

	/**
	 * @return value of UniqueId
	 */
	public final java.lang.String getUniqueId()
	{
		return getUniqueId(getContext());
	}

	/**
	 * @param context
	 * @return value of UniqueId
	 */
	public final java.lang.String getUniqueId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UniqueId.toString());
	}

	/**
	 * Set value of UniqueId
	 * @param uniqueid
	 */
	public final void setUniqueId(java.lang.String uniqueid)
	{
		setUniqueId(getContext(), uniqueid);
	}

	/**
	 * Set value of UniqueId
	 * @param context
	 * @param uniqueid
	 */
	public final void setUniqueId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uniqueid)
	{
		getMendixObject().setValue(context, MemberNames.UniqueId.toString(), uniqueid);
	}

	/**
	 * @return value of UserAgent
	 */
	public final java.lang.String getUserAgent()
	{
		return getUserAgent(getContext());
	}

	/**
	 * @param context
	 * @return value of UserAgent
	 */
	public final java.lang.String getUserAgent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserAgent.toString());
	}

	/**
	 * Set value of UserAgent
	 * @param useragent
	 */
	public final void setUserAgent(java.lang.String useragent)
	{
		setUserAgent(getContext(), useragent);
	}

	/**
	 * Set value of UserAgent
	 * @param context
	 * @param useragent
	 */
	public final void setUserAgent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String useragent)
	{
		getMendixObject().setValue(context, MemberNames.UserAgent.toString(), useragent);
	}

	/**
	 * @return value of Version
	 */
	public final java.lang.String getVersion()
	{
		return getVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of Version
	 */
	public final java.lang.String getVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Version.toString());
	}

	/**
	 * Set value of Version
	 * @param version
	 */
	public final void setVersion(java.lang.String version)
	{
		setVersion(getContext(), version);
	}

	/**
	 * Set value of Version
	 * @param context
	 * @param version
	 */
	public final void setVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String version)
	{
		getMendixObject().setValue(context, MemberNames.Version.toString(), version);
	}

	/**
	 * @return value of Is24Hour
	 */
	public final java.lang.Boolean getIs24Hour()
	{
		return getIs24Hour(getContext());
	}

	/**
	 * @param context
	 * @return value of Is24Hour
	 */
	public final java.lang.Boolean getIs24Hour(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Is24Hour.toString());
	}

	/**
	 * Set value of Is24Hour
	 * @param is24hour
	 */
	public final void setIs24Hour(java.lang.Boolean is24hour)
	{
		setIs24Hour(getContext(), is24hour);
	}

	/**
	 * Set value of Is24Hour
	 * @param context
	 * @param is24hour
	 */
	public final void setIs24Hour(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean is24hour)
	{
		getMendixObject().setValue(context, MemberNames.Is24Hour.toString(), is24hour);
	}

	/**
	 * @return value of IsEmulator
	 */
	public final java.lang.Boolean getIsEmulator()
	{
		return getIsEmulator(getContext());
	}

	/**
	 * @param context
	 * @return value of IsEmulator
	 */
	public final java.lang.Boolean getIsEmulator(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsEmulator.toString());
	}

	/**
	 * Set value of IsEmulator
	 * @param isemulator
	 */
	public final void setIsEmulator(java.lang.Boolean isemulator)
	{
		setIsEmulator(getContext(), isemulator);
	}

	/**
	 * Set value of IsEmulator
	 * @param context
	 * @param isemulator
	 */
	public final void setIsEmulator(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isemulator)
	{
		getMendixObject().setValue(context, MemberNames.IsEmulator.toString(), isemulator);
	}

	/**
	 * @return value of IsTablet
	 */
	public final java.lang.Boolean getIsTablet()
	{
		return getIsTablet(getContext());
	}

	/**
	 * @param context
	 * @return value of IsTablet
	 */
	public final java.lang.Boolean getIsTablet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsTablet.toString());
	}

	/**
	 * Set value of IsTablet
	 * @param istablet
	 */
	public final void setIsTablet(java.lang.Boolean istablet)
	{
		setIsTablet(getContext(), istablet);
	}

	/**
	 * Set value of IsTablet
	 * @param context
	 * @param istablet
	 */
	public final void setIsTablet(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean istablet)
	{
		getMendixObject().setValue(context, MemberNames.IsTablet.toString(), istablet);
	}

	/**
	 * @return value of IsLandscape
	 */
	public final java.lang.Boolean getIsLandscape()
	{
		return getIsLandscape(getContext());
	}

	/**
	 * @param context
	 * @return value of IsLandscape
	 */
	public final java.lang.Boolean getIsLandscape(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsLandscape.toString());
	}

	/**
	 * Set value of IsLandscape
	 * @param islandscape
	 */
	public final void setIsLandscape(java.lang.Boolean islandscape)
	{
		setIsLandscape(getContext(), islandscape);
	}

	/**
	 * Set value of IsLandscape
	 * @param context
	 * @param islandscape
	 */
	public final void setIsLandscape(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean islandscape)
	{
		getMendixObject().setValue(context, MemberNames.IsLandscape.toString(), islandscape);
	}

	/**
	 * @return value of HasNotch
	 */
	public final java.lang.Boolean getHasNotch()
	{
		return getHasNotch(getContext());
	}

	/**
	 * @param context
	 * @return value of HasNotch
	 */
	public final java.lang.Boolean getHasNotch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasNotch.toString());
	}

	/**
	 * Set value of HasNotch
	 * @param hasnotch
	 */
	public final void setHasNotch(java.lang.Boolean hasnotch)
	{
		setHasNotch(getContext(), hasnotch);
	}

	/**
	 * Set value of HasNotch
	 * @param context
	 * @param hasnotch
	 */
	public final void setHasNotch(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasnotch)
	{
		getMendixObject().setValue(context, MemberNames.HasNotch.toString(), hasnotch);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return deviceInfoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativemobileresources.proxies.DeviceInfo that = (nativemobileresources.proxies.DeviceInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "NativeMobileResources.DeviceInfo";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
