// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public class Parameter
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject parameterMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeMobileResources.Parameter";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Href("Href"),
		Protocol("Protocol"),
		PathName("PathName"),
		Query("Query"),
		Path0("Path0"),
		Path1("Path1"),
		Path2("Path2"),
		Hash("Hash"),
		Host("Host");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Parameter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "NativeMobileResources.Parameter"));
	}

	protected Parameter(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject parameterMendixObject)
	{
		if (parameterMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("NativeMobileResources.Parameter", parameterMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a NativeMobileResources.Parameter");

		this.parameterMendixObject = parameterMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Parameter.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static nativemobileresources.proxies.Parameter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nativemobileresources.proxies.Parameter.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static nativemobileresources.proxies.Parameter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativemobileresources.proxies.Parameter(context, mendixObject);
	}

	public static nativemobileresources.proxies.Parameter load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativemobileresources.proxies.Parameter.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Href
	 */
	public final java.lang.String getHref()
	{
		return getHref(getContext());
	}

	/**
	 * @param context
	 * @return value of Href
	 */
	public final java.lang.String getHref(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Href.toString());
	}

	/**
	 * Set value of Href
	 * @param href
	 */
	public final void setHref(java.lang.String href)
	{
		setHref(getContext(), href);
	}

	/**
	 * Set value of Href
	 * @param context
	 * @param href
	 */
	public final void setHref(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String href)
	{
		getMendixObject().setValue(context, MemberNames.Href.toString(), href);
	}

	/**
	 * @return value of Protocol
	 */
	public final java.lang.String getProtocol()
	{
		return getProtocol(getContext());
	}

	/**
	 * @param context
	 * @return value of Protocol
	 */
	public final java.lang.String getProtocol(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Protocol.toString());
	}

	/**
	 * Set value of Protocol
	 * @param protocol
	 */
	public final void setProtocol(java.lang.String protocol)
	{
		setProtocol(getContext(), protocol);
	}

	/**
	 * Set value of Protocol
	 * @param context
	 * @param protocol
	 */
	public final void setProtocol(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String protocol)
	{
		getMendixObject().setValue(context, MemberNames.Protocol.toString(), protocol);
	}

	/**
	 * @return value of PathName
	 */
	public final java.lang.String getPathName()
	{
		return getPathName(getContext());
	}

	/**
	 * @param context
	 * @return value of PathName
	 */
	public final java.lang.String getPathName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PathName.toString());
	}

	/**
	 * Set value of PathName
	 * @param pathname
	 */
	public final void setPathName(java.lang.String pathname)
	{
		setPathName(getContext(), pathname);
	}

	/**
	 * Set value of PathName
	 * @param context
	 * @param pathname
	 */
	public final void setPathName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pathname)
	{
		getMendixObject().setValue(context, MemberNames.PathName.toString(), pathname);
	}

	/**
	 * @return value of Query
	 */
	public final java.lang.String getQuery()
	{
		return getQuery(getContext());
	}

	/**
	 * @param context
	 * @return value of Query
	 */
	public final java.lang.String getQuery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Query.toString());
	}

	/**
	 * Set value of Query
	 * @param query
	 */
	public final void setQuery(java.lang.String query)
	{
		setQuery(getContext(), query);
	}

	/**
	 * Set value of Query
	 * @param context
	 * @param query
	 */
	public final void setQuery(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String query)
	{
		getMendixObject().setValue(context, MemberNames.Query.toString(), query);
	}

	/**
	 * @return value of Path0
	 */
	public final java.lang.String getPath0()
	{
		return getPath0(getContext());
	}

	/**
	 * @param context
	 * @return value of Path0
	 */
	public final java.lang.String getPath0(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Path0.toString());
	}

	/**
	 * Set value of Path0
	 * @param path0
	 */
	public final void setPath0(java.lang.String path0)
	{
		setPath0(getContext(), path0);
	}

	/**
	 * Set value of Path0
	 * @param context
	 * @param path0
	 */
	public final void setPath0(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String path0)
	{
		getMendixObject().setValue(context, MemberNames.Path0.toString(), path0);
	}

	/**
	 * @return value of Path1
	 */
	public final java.lang.String getPath1()
	{
		return getPath1(getContext());
	}

	/**
	 * @param context
	 * @return value of Path1
	 */
	public final java.lang.String getPath1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Path1.toString());
	}

	/**
	 * Set value of Path1
	 * @param path1
	 */
	public final void setPath1(java.lang.String path1)
	{
		setPath1(getContext(), path1);
	}

	/**
	 * Set value of Path1
	 * @param context
	 * @param path1
	 */
	public final void setPath1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String path1)
	{
		getMendixObject().setValue(context, MemberNames.Path1.toString(), path1);
	}

	/**
	 * @return value of Path2
	 */
	public final java.lang.String getPath2()
	{
		return getPath2(getContext());
	}

	/**
	 * @param context
	 * @return value of Path2
	 */
	public final java.lang.String getPath2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Path2.toString());
	}

	/**
	 * Set value of Path2
	 * @param path2
	 */
	public final void setPath2(java.lang.String path2)
	{
		setPath2(getContext(), path2);
	}

	/**
	 * Set value of Path2
	 * @param context
	 * @param path2
	 */
	public final void setPath2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String path2)
	{
		getMendixObject().setValue(context, MemberNames.Path2.toString(), path2);
	}

	/**
	 * @return value of Hash
	 */
	public final java.lang.String getHash()
	{
		return getHash(getContext());
	}

	/**
	 * @param context
	 * @return value of Hash
	 */
	public final java.lang.String getHash(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Hash.toString());
	}

	/**
	 * Set value of Hash
	 * @param hash
	 */
	public final void setHash(java.lang.String hash)
	{
		setHash(getContext(), hash);
	}

	/**
	 * Set value of Hash
	 * @param context
	 * @param hash
	 */
	public final void setHash(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hash)
	{
		getMendixObject().setValue(context, MemberNames.Hash.toString(), hash);
	}

	/**
	 * @return value of Host
	 */
	public final java.lang.String getHost()
	{
		return getHost(getContext());
	}

	/**
	 * @param context
	 * @return value of Host
	 */
	public final java.lang.String getHost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Host.toString());
	}

	/**
	 * Set value of Host
	 * @param host
	 */
	public final void setHost(java.lang.String host)
	{
		setHost(getContext(), host);
	}

	/**
	 * Set value of Host
	 * @param context
	 * @param host
	 */
	public final void setHost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String host)
	{
		getMendixObject().setValue(context, MemberNames.Host.toString(), host);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return parameterMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativemobileresources.proxies.Parameter that = (nativemobileresources.proxies.Parameter) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "NativeMobileResources.Parameter";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
