// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package administration.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Administration module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder changeMyPasswordBuilder(
		administration.proxies.AccountPasswordData _accountPasswordData
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Administration.ChangeMyPassword");
		builder = builder.withParam("AccountPasswordData", _accountPasswordData);
		return builder;
	}

	public static void changeMyPassword(
		IContext context,
		administration.proxies.AccountPasswordData _accountPasswordData
	)
	{
		changeMyPasswordBuilder(
				_accountPasswordData
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder changePasswordBuilder(
		administration.proxies.AccountPasswordData _accountPasswordData
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Administration.ChangePassword");
		builder = builder.withParam("AccountPasswordData", _accountPasswordData);
		return builder;
	}

	public static void changePassword(
		IContext context,
		administration.proxies.AccountPasswordData _accountPasswordData
	)
	{
		changePasswordBuilder(
				_accountPasswordData
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder manageMyAccountBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Administration.ManageMyAccount");
		return builder;
	}

	public static void manageMyAccount(IContext context)
	{
		manageMyAccountBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder newAccountBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Administration.NewAccount");
		return builder;
	}

	public static void newAccount(IContext context)
	{
		newAccountBuilder().execute(context);
	}
	/**
	 * Create a new user object and change the default attribute values so the user will be handled as a webservice user.
	 * Finally open the User_NewEdit form so all remaing user information can be set.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder newWebServiceAccountBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Administration.NewWebServiceAccount");
		return builder;
	}

	/**
	 * Create a new user object and change the default attribute values so the user will be handled as a webservice user.
	 * Finally open the User_NewEdit form so all remaing user information can be set.
	 */
	public static void newWebServiceAccount(IContext context)
	{
		newWebServiceAccountBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder retrieveTimeZonesBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Administration.RetrieveTimeZones");
		return builder;
	}

	public static java.util.List<system.proxies.TimeZone> retrieveTimeZones(IContext context)
	{
		Object result = retrieveTimeZonesBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> system.proxies.TimeZone.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder saveNewAccountBuilder(
		administration.proxies.AccountPasswordData _accountPasswordData
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Administration.SaveNewAccount");
		builder = builder.withParam("AccountPasswordData", _accountPasswordData);
		return builder;
	}

	public static void saveNewAccount(
		IContext context,
		administration.proxies.AccountPasswordData _accountPasswordData
	)
	{
		saveNewAccountBuilder(
				_accountPasswordData
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder showMyPasswordFormBuilder(
		administration.proxies.Account _account
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Administration.ShowMyPasswordForm");
		builder = builder.withParam("Account", _account);
		return builder;
	}

	public static void showMyPasswordForm(
		IContext context,
		administration.proxies.Account _account
	)
	{
		showMyPasswordFormBuilder(
				_account
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder showPasswordFormBuilder(
		administration.proxies.Account _account
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Administration.ShowPasswordForm");
		builder = builder.withParam("Account", _account);
		return builder;
	}

	public static void showPasswordForm(
		IContext context,
		administration.proxies.Account _account
	)
	{
		showPasswordFormBuilder(
				_account
			)
			.execute(context);
	}
}
