// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { Platform, NativeModules } from 'react-native';
import { PERMISSIONS as PERMISSIONS$1, check } from 'react-native-permissions';

// BEGIN EXTRA CODE
const PERMISSIONS = {
    ANDROID: {
        ...PERMISSIONS$1.ANDROID,
        SCHEDULE_EXACT_ALARM: "android.permission.SCHEDULE_EXACT_ALARM"
    },
    IOS: PERMISSIONS$1.IOS
};
function mapPermissionName(permissionName) {
    if (Platform.OS === "ios") {
        const nameWithoutSuffix = permissionName.replace("_IOS", "");
        return PERMISSIONS.IOS[nameWithoutSuffix];
    }
    const nameWithoutSuffix = permissionName.replace("_ANDROID", "");
    return PERMISSIONS.ANDROID[nameWithoutSuffix];
}
async function checkScheduleAlarm() {
    if (NativeModules && !NativeModules.ScheduleEA) {
        return Promise.reject(new Error("ScheduleEA module is not available in your app"));
    }
    if (Platform.OS !== "android") {
        return Promise.resolve("granted");
    }
    const checkPermissionPromise = new Promise(resolve => {
        NativeModules.ScheduleEA.checkPermission((isEnabled) => {
            resolve(isEnabled);
        });
    });
    return checkPermissionPromise.then(result => {
        return Promise.resolve(result ? "granted" : "blocked");
    });
}
// END EXTRA CODE

/**
 * @param {undefined|"APP_TRACKING_TRANSPARENCY_IOS"|"BLUETOOTH_PERIPHERAL_IOS"|"CAMERA_IOS"|"CALENDARS_IOS"|"CONTACTS_IOS"|"FACE_ID_IOS"|"LOCATION_ALWAYS_IOS"|"LOCATION_WHEN_IN_USE_IOS"|"MEDIA_LIBRARY_IOS"|"MICROPHONE_IOS"|"MOTION_IOS"|"PHOTO_LIBRARY_IOS"|"PHOTO_LIBRARY_ADD_ONLY_IOS"|"REMINDERS_IOS"|"SIRI_IOS"|"SPEECH_RECOGNITION_IOS"|"STOREKIT_IOS"|"ACCEPT_HANDOVER_ANDROID"|"ACCESS_BACKGROUND_LOCATION_ANDROID"|"ACCESS_COARSE_LOCATION_ANDROID"|"ACCESS_FINE_LOCATION_ANDROID"|"ACCESS_MEDIA_LOCATION_ANDROID"|"ACTIVITY_RECOGNITION_ANDROID"|"ADD_VOICEMAIL_ANDROID"|"ANSWER_PHONE_CALLS_ANDROID"|"BLUETOOTH_ADVERTISE_ANDROID"|"BLUETOOTH_CONNECT_ANDROID"|"BLUETOOTH_SCAN_ANDROID"|"BODY_SENSORS_ANDROID"|"CALL_PHONE_ANDROID"|"CAMERA_ANDROID"|"GET_ACCOUNTS_ANDROID"|"PROCESS_OUTGOING_CALLS_ANDROID"|"READ_CALENDAR_ANDROID"|"READ_CALL_LOG_ANDROID"|"READ_CONTACTS_ANDROID"|"READ_EXTERNAL_STORAGE_ANDROID"|"READ_PHONE_NUMBERS_ANDROID"|"READ_PHONE_STATE_ANDROID"|"READ_SMS_ANDROID"|"RECEIVE_MMS_ANDROID"|"RECEIVE_SMS_ANDROID"|"RECEIVE_WAP_PUSH_ANDROID"|"RECORD_AUDIO_ANDROID"|"SEND_SMS_ANDROID"|"USE_SIP_ANDROID"|"WRITE_CALENDAR_ANDROID"|"WRITE_CALL_LOG_ANDROID"|"WRITE_CONTACTS_ANDROID"|"WRITE_EXTERNAL_STORAGE_ANDROID"|"SCHEDULE_EXACT_ALARM_ANDROID"|"READ_MEDIA_VISUAL_USER_SELECTED_ANDROID"|"READ_MEDIA_VIDEO_ANDROID"|"READ_MEDIA_IMAGES_ANDROID"|"READ_MEDIA_AUDIO_ANDROID"|"NEARBY_WIFI_DEVICES_ANDROID"|"BODY_SENSORS_BACKGROUND_ANDROID"} permission - This field is required.
 * @returns {Promise.<undefined|"unavailable"|"denied"|"limited"|"granted"|"blocked">}
 */
export async function CheckGenericPermission(permission) {
	// BEGIN USER CODE
    if (!permission) {
        return Promise.reject(new Error("Input parameter 'permission' is required"));
    }
    const mappedPermissionName = mapPermissionName(permission);
    if (!mappedPermissionName) {
        console.error(`${permission} permission is not found`);
        return Promise.resolve("unavailable");
    }
    return mappedPermissionName === PERMISSIONS.ANDROID.SCHEDULE_EXACT_ALARM
        ? checkScheduleAlarm()
        : check(mappedPermissionName);
	// END USER CODE
}
