// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import { Alert, Platform } from 'react-native';
import { check, RESULTS, request, openSettings, PERMISSIONS } from 'react-native-permissions';

// BEGIN EXTRA CODE
function handleBlockedPermission(permission) {
    const permissionName = permission.replace(/_IOS|_ANDROID/, "");
    Alert.alert("", `Please allow ${permissionName} access`, [
        { text: "go to settings", onPress: () => openSettings() },
        { text: "cancel" }
    ]);
}
function mapPermissionName(permissionName) {
    if (Platform.OS === "ios") {
        const nameWithoutSuffix = permissionName.replace("_IOS", "");
        return PERMISSIONS.IOS[nameWithoutSuffix];
    }
    else if (Platform.OS === "android") {
        const nameWithoutSuffix = permissionName.replace("_ANDROID", "");
        return PERMISSIONS.ANDROID[nameWithoutSuffix];
    }
}
// END EXTRA CODE

/**
 * @param {"NativeMobileResources.Enum_Permissions.APP_TRACKING_TRANSPARENCY_IOS"|"NativeMobileResources.Enum_Permissions.BLUETOOTH_PERIPHERAL_IOS"|"NativeMobileResources.Enum_Permissions.CAMERA_IOS"|"NativeMobileResources.Enum_Permissions.CALENDARS_IOS"|"NativeMobileResources.Enum_Permissions.CONTACTS_IOS"|"NativeMobileResources.Enum_Permissions.FACE_ID_IOS"|"NativeMobileResources.Enum_Permissions.LOCATION_ALWAYS_IOS"|"NativeMobileResources.Enum_Permissions.LOCATION_WHEN_IN_USE_IOS"|"NativeMobileResources.Enum_Permissions.MEDIA_LIBRARY_IOS"|"NativeMobileResources.Enum_Permissions.MICROPHONE_IOS"|"NativeMobileResources.Enum_Permissions.MOTION_IOS"|"NativeMobileResources.Enum_Permissions.PHOTO_LIBRARY_IOS"|"NativeMobileResources.Enum_Permissions.PHOTO_LIBRARY_ADD_ONLY_IOS"|"NativeMobileResources.Enum_Permissions.REMINDERS_IOS"|"NativeMobileResources.Enum_Permissions.SIRI_IOS"|"NativeMobileResources.Enum_Permissions.SPEECH_RECOGNITION_IOS"|"NativeMobileResources.Enum_Permissions.STOREKIT_IOS"|"NativeMobileResources.Enum_Permissions.ACCEPT_HANDOVER_ANDROID"|"NativeMobileResources.Enum_Permissions.ACCESS_BACKGROUND_LOCATION_ANDROID"|"NativeMobileResources.Enum_Permissions.ACCESS_COARSE_LOCATION_ANDROID"|"NativeMobileResources.Enum_Permissions.ACCESS_FINE_LOCATION_ANDROID"|"NativeMobileResources.Enum_Permissions.ACCESS_MEDIA_LOCATION_ANDROID"|"NativeMobileResources.Enum_Permissions.ACTIVITY_RECOGNITION_ANDROID"|"NativeMobileResources.Enum_Permissions.ADD_VOICEMAIL_ANDROID"|"NativeMobileResources.Enum_Permissions.ANSWER_PHONE_CALLS_ANDROID"|"NativeMobileResources.Enum_Permissions.BLUETOOTH_ADVERTISE_ANDROID"|"NativeMobileResources.Enum_Permissions.BLUETOOTH_CONNECT_ANDROID"|"NativeMobileResources.Enum_Permissions.BLUETOOTH_SCAN_ANDROID"|"NativeMobileResources.Enum_Permissions.BODY_SENSORS_ANDROID"|"NativeMobileResources.Enum_Permissions.CALL_PHONE_ANDROID"|"NativeMobileResources.Enum_Permissions.CAMERA_ANDROID"|"NativeMobileResources.Enum_Permissions.GET_ACCOUNTS_ANDROID"|"NativeMobileResources.Enum_Permissions.PROCESS_OUTGOING_CALLS_ANDROID"|"NativeMobileResources.Enum_Permissions.READ_CALENDAR_ANDROID"|"NativeMobileResources.Enum_Permissions.READ_CALL_LOG_ANDROID"|"NativeMobileResources.Enum_Permissions.READ_CONTACTS_ANDROID"|"NativeMobileResources.Enum_Permissions.READ_EXTERNAL_STORAGE_ANDROID"|"NativeMobileResources.Enum_Permissions.READ_PHONE_NUMBERS_ANDROID"|"NativeMobileResources.Enum_Permissions.READ_PHONE_STATE_ANDROID"|"NativeMobileResources.Enum_Permissions.READ_SMS_ANDROID"|"NativeMobileResources.Enum_Permissions.RECEIVE_MMS_ANDROID"|"NativeMobileResources.Enum_Permissions.RECEIVE_SMS_ANDROID"|"NativeMobileResources.Enum_Permissions.RECEIVE_WAP_PUSH_ANDROID"|"NativeMobileResources.Enum_Permissions.RECORD_AUDIO_ANDROID"|"NativeMobileResources.Enum_Permissions.SEND_SMS_ANDROID"|"NativeMobileResources.Enum_Permissions.USE_SIP_ANDROID"|"NativeMobileResources.Enum_Permissions.WRITE_CALENDAR_ANDROID"|"NativeMobileResources.Enum_Permissions.WRITE_CALL_LOG_ANDROID"|"NativeMobileResources.Enum_Permissions.WRITE_CONTACTS_ANDROID"|"NativeMobileResources.Enum_Permissions.WRITE_EXTERNAL_STORAGE_ANDROID"} permission - This field is required.
 * @returns {Promise.<"NativeMobileResources.Enum_PermissionStatus.unavailable"|"NativeMobileResources.Enum_PermissionStatus.denied"|"NativeMobileResources.Enum_PermissionStatus.limited"|"NativeMobileResources.Enum_PermissionStatus.granted"|"NativeMobileResources.Enum_PermissionStatus.blocked">}
 */
export async function RequestGenericPermission(permission) {
	// BEGIN USER CODE
    if (!permission) {
        return Promise.reject(new Error("Input parameter 'permission' is required"));
    }
    const mappedPermissionName = mapPermissionName(permission);
    if (!mappedPermissionName) {
        console.error(`${permission} permission is not found`);
        return Promise.resolve("unavailable");
    }
    const permissionStatus = await check(mappedPermissionName);
    switch (permissionStatus) {
        case RESULTS.GRANTED:
        case RESULTS.UNAVAILABLE:
        case RESULTS.LIMITED:
            return permissionStatus;
        case RESULTS.BLOCKED:
            handleBlockedPermission(permission);
            return RESULTS.BLOCKED;
        case RESULTS.DENIED:
            return request(mappedPermissionName);
    }
	// END USER CODE
}
