// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_designsystem.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Atlas_DesignSystem module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSu_CleanTakePictureEntitiesBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.ASu_CleanTakePictureEntities");
		return builder;
	}

	public static void aSu_CleanTakePictureEntities(IContext context)
	{
		aSu_CleanTakePictureEntitiesBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSu_RestockAtlasContinentObjectEntitiesBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.ASu_RestockAtlasContinentObjectEntities");
		return builder;
	}

	public static void aSu_RestockAtlasContinentObjectEntities(IContext context)
	{
		aSu_RestockAtlasContinentObjectEntitiesBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSu_RestockAtlasGenericObjectEntitiesBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.ASu_RestockAtlasGenericObjectEntities");
		return builder;
	}

	public static void aSu_RestockAtlasGenericObjectEntities(IContext context)
	{
		aSu_RestockAtlasGenericObjectEntitiesBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSu_RestockAtlasLocationDateEntitiesBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.ASu_RestockAtlasLocationDateEntities");
		return builder;
	}

	public static void aSu_RestockAtlasLocationDateEntities(IContext context)
	{
		aSu_RestockAtlasLocationDateEntitiesBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSu_RestockAtlasPeopleEntitiesBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.ASu_RestockAtlasPeopleEntities");
		return builder;
	}

	public static void aSu_RestockAtlasPeopleEntities(IContext context)
	{
		aSu_RestockAtlasPeopleEntitiesBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSu_RestockAtlasStatisticsEntitiesBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.ASu_RestockAtlasStatisticsEntities");
		return builder;
	}

	public static void aSu_RestockAtlasStatisticsEntities(IContext context)
	{
		aSu_RestockAtlasStatisticsEntitiesBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSu_RestockTaskInboxEntitiesBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.ASu_RestockTaskInboxEntities");
		return builder;
	}

	public static void aSu_RestockTaskInboxEntities(IContext context)
	{
		aSu_RestockTaskInboxEntitiesBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSu_RunModuleSpecificMFsBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.ASu_RunModuleSpecificMFs");
		return builder;
	}

	public static boolean aSu_RunModuleSpecificMFs(IContext context)
	{
		Object result = aSu_RunModuleSpecificMFsBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder comboBox_DefaultBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.ComboBox_Default");
		return builder;
	}

	public static atlas_designsystem.proxies.UserList comboBox_Default(IContext context)
	{
		Object result = comboBox_DefaultBuilder().execute(context);
		return result == null ? null : atlas_designsystem.proxies.UserList.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_ChartData_StaticSet1Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.DS_ChartData_StaticSet1");
		return builder;
	}

	public static java.util.List<atlas_designsystem.proxies.ChartsDataMap> dS_ChartData_StaticSet1(IContext context)
	{
		Object result = dS_ChartData_StaticSet1Builder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> atlas_designsystem.proxies.ChartsDataMap.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_ChartData_StaticSet2Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.DS_ChartData_StaticSet2");
		return builder;
	}

	public static java.util.List<atlas_designsystem.proxies.ChartsDataMap> dS_ChartData_StaticSet2(IContext context)
	{
		Object result = dS_ChartData_StaticSet2Builder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> atlas_designsystem.proxies.ChartsDataMap.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_EmptyRatingBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.DS_EmptyRating");
		return builder;
	}

	public static atlas_ui_data.proxies.AtlasGenericObject dS_EmptyRating(IContext context)
	{
		Object result = dS_EmptyRatingBuilder().execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasGenericObject.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_MaxRatingBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.DS_MaxRating");
		return builder;
	}

	public static atlas_ui_data.proxies.AtlasGenericObject dS_MaxRating(IContext context)
	{
		Object result = dS_MaxRatingBuilder().execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasGenericObject.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_ProductListBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.DS_ProductList");
		return builder;
	}

	public static java.util.List<atlas_designsystem.proxies.Product> dS_ProductList(IContext context)
	{
		Object result = dS_ProductListBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> atlas_designsystem.proxies.Product.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_RangeSliderBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.DS_RangeSlider");
		return builder;
	}

	public static atlas_designsystem.proxies.RangeSlider dS_RangeSlider(IContext context)
	{
		Object result = dS_RangeSliderBuilder().execute(context);
		return result == null ? null : atlas_designsystem.proxies.RangeSlider.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_SliderBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.DS_Slider");
		return builder;
	}

	public static atlas_designsystem.proxies.Slider dS_Slider(IContext context)
	{
		Object result = dS_SliderBuilder().execute(context);
		return result == null ? null : atlas_designsystem.proxies.Slider.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_TreenodeBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.DS_Treenode");
		return builder;
	}

	public static java.util.List<atlas_ui_data.proxies.AtlasGenericObject> dS_Treenode(IContext context)
	{
		Object result = dS_TreenodeBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> atlas_ui_data.proxies.AtlasGenericObject.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_DataString_to_ChartsDataMapListBuilder(
		java.lang.String _dataString
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Atlas_DesignSystem.MF_DataString_to_ChartsDataMapList");
		builder = builder.withParam("DataString", _dataString);
		return builder;
	}

	public static java.util.List<atlas_designsystem.proxies.ChartsDataMap> mF_DataString_to_ChartsDataMapList(
		IContext context,
		java.lang.String _dataString
	)
	{
		Object result = mF_DataString_to_ChartsDataMapListBuilder(
				_dataString
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> atlas_designsystem.proxies.ChartsDataMap.initialize(context, obj));
	}
}
