// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_designsystem.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Atlas_DesignSystem module
	public static boolean aCT_ConvertBase64ToImage(IContext context, atlas_designsystem.proxies.ScreenshotTaker _screenShotTaker)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ScreenShotTaker", _screenShotTaker == null ? null : _screenShotTaker.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("Atlas_DesignSystem.ACT_ConvertBase64ToImage").withParams(params).execute(context);
	}
	public static void aCT_DeleteScreenshotsBuildingBlocks(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Atlas_DesignSystem.ACT_DeleteScreenshotsBuildingBlocks").withParams(params).execute(context);
	}
	public static void aCT_DeleteScreenshotsPageTemplates(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Atlas_DesignSystem.ACT_DeleteScreenshotsPageTemplates").withParams(params).execute(context);
	}
	public static void aCT_DeleteScreenshotsWidgets(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Atlas_DesignSystem.ACT_DeleteScreenshotsWidgets").withParams(params).execute(context);
	}
	public static void aCT_SaveScreenshotsBuildingBlocksToFile(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Atlas_DesignSystem.ACT_SaveScreenshotsBuildingBlocksToFile").withParams(params).execute(context);
	}
	public static void aCT_SaveScreenshotsPageTemplatesToFile(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Atlas_DesignSystem.ACT_SaveScreenshotsPageTemplatesToFile").withParams(params).execute(context);
	}
	public static void aCT_SaveScreenshotsWidgetsToFile(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Atlas_DesignSystem.ACT_SaveScreenshotsWidgetsToFile").withParams(params).execute(context);
	}
	public static void aSu_RestockAtlasGenericObjectEntities(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Atlas_DesignSystem.ASu_RestockAtlasGenericObjectEntities").withParams(params).execute(context);
	}
	public static void aSu_RestockAtlasLocationDateEntities(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Atlas_DesignSystem.ASu_RestockAtlasLocationDateEntities").withParams(params).execute(context);
	}
	public static void aSu_RestockAtlasPeopleEntities(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Atlas_DesignSystem.ASu_RestockAtlasPeopleEntities").withParams(params).execute(context);
	}
	public static void aSu_RestockAtlasStatisticsEntities(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Atlas_DesignSystem.ASu_RestockAtlasStatisticsEntities").withParams(params).execute(context);
	}
	public static void aSu_RestockTaskInboxEntities(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Atlas_DesignSystem.ASu_RestockTaskInboxEntities").withParams(params).execute(context);
	}
	public static boolean aSu_RunModuleSpecificMFs(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("Atlas_DesignSystem.ASu_RunModuleSpecificMFs").withParams(params).execute(context);
	}
	public static atlas_ui_data.proxies.AtlasGenericObject dS_EmptyRating(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Atlas_DesignSystem.DS_EmptyRating").withParams(params).execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasGenericObject.initialize(context, result);
	}
	public static atlas_ui_data.proxies.AtlasGenericObject dS_MaxRating(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Atlas_DesignSystem.DS_MaxRating").withParams(params).execute(context);
		return result == null ? null : atlas_ui_data.proxies.AtlasGenericObject.initialize(context, result);
	}
	public static atlas_designsystem.proxies.RangeSlider dS_RangeSlider(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Atlas_DesignSystem.DS_RangeSlider").withParams(params).execute(context);
		return result == null ? null : atlas_designsystem.proxies.RangeSlider.initialize(context, result);
	}
	public static atlas_designsystem.proxies.Slider dS_Slider(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Atlas_DesignSystem.DS_Slider").withParams(params).execute(context);
		return result == null ? null : atlas_designsystem.proxies.Slider.initialize(context, result);
	}
}