// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the CommunityCommons module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder assertTrueBuilder(
		boolean _valueToAssert
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CommunityCommons.AssertTrue");
		builder = builder.withParam("valueToAssert", _valueToAssert);
		return builder;
	}

	public static void assertTrue(
		IContext context,
		boolean _valueToAssert
	)
	{
		assertTrueBuilder(
				_valueToAssert
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder assertTrue_2Builder(
		boolean _valueToAssert,
		java.lang.String _message
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CommunityCommons.AssertTrue_2");
		builder = builder.withParam("valueToAssert", _valueToAssert);
		builder = builder.withParam("message", _message);
		return builder;
	}

	public static void assertTrue_2(
		IContext context,
		boolean _valueToAssert,
		java.lang.String _message
	)
	{
		assertTrue_2Builder(
				_valueToAssert,
				_message
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createUserIfNotExistsBuilder(
		java.lang.String _username,
		java.lang.String _role,
		java.lang.String _password,
		boolean _webserviceUser
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CommunityCommons.CreateUserIfNotExists");
		builder = builder.withParam("Username", _username);
		builder = builder.withParam("Role", _role);
		builder = builder.withParam("Password", _password);
		builder = builder.withParam("WebserviceUser", _webserviceUser);
		return builder;
	}

	public static void createUserIfNotExists(
		IContext context,
		java.lang.String _username,
		java.lang.String _role,
		java.lang.String _password,
		boolean _webserviceUser
	)
	{
		createUserIfNotExistsBuilder(
				_username,
				_role,
				_password,
				_webserviceUser
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder updateUserHelperBuilder(
		java.lang.String _username,
		java.lang.String _role,
		java.lang.String _password,
		boolean _webserviceUser,
		system.proxies.User _user
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CommunityCommons.UpdateUserHelper");
		builder = builder.withParam("Username", _username);
		builder = builder.withParam("Role", _role);
		builder = builder.withParam("Password", _password);
		builder = builder.withParam("WebserviceUser", _webserviceUser);
		builder = builder.withParam("User", _user);
		return builder;
	}

	public static void updateUserHelper(
		IContext context,
		java.lang.String _username,
		java.lang.String _role,
		java.lang.String _password,
		boolean _webserviceUser,
		system.proxies.User _user
	)
	{
		updateUserHelperBuilder(
				_username,
				_role,
				_password,
				_webserviceUser,
				_user
			)
			.execute(context);
	}
}
