// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package workflowcommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_UserTaskView_GenerateKey extends UserAction<java.lang.String>
{
	/** @deprecated use userTaskView.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __userTaskView;
	private final workflowcommons.proxies.UserTaskView userTaskView;

	public JA_UserTaskView_GenerateKey(
		IContext context,
		IMendixObject _userTaskView
	)
	{
		super(context);
		this.__userTaskView = _userTaskView;
		this.userTaskView = _userTaskView == null ? null : workflowcommons.proxies.UserTaskView.initialize(getContext(), _userTaskView);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (userTaskView == null)
			throw new RuntimeException("No UserTaskView object provided");
		
		return Long.toHexString(userTaskView.getMendixObject().getId().toLong());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_UserTaskView_GenerateKey";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
