// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package workflowcommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class JA_WorkflowUserTask_GetKey extends UserAction<java.lang.String>
{
	/** @deprecated use workflowUserTask.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __workflowUserTask;
	private final system.proxies.WorkflowUserTask workflowUserTask;

	public JA_WorkflowUserTask_GetKey(
		IContext context,
		IMendixObject _workflowUserTask
	)
	{
		super(context);
		this.__workflowUserTask = _workflowUserTask;
		this.workflowUserTask = _workflowUserTask == null ? null : system.proxies.WorkflowUserTask.initialize(getContext(), _workflowUserTask);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_WorkflowUserTask_GetKey";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
