// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the System module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder showHomePageBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("System.ShowHomePage");
		return builder;
	}

	public static void showHomePage(IContext context)
	{
		showHomePageBuilder().execute(context);
	}
}
